### ISSUE TITLE
N4JS subtypes of Function are callable which leads to runtime failures

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#105]
In N4JS it is possible to subclass the built-in type Function. On a conceptual level, this might make sense, but at runtime this is not supported.

Consider the following (valid) code:

```
class A extends Function {}

var a : Function = new A();
a();
```

This results in 

```
(SystemJS) a is not a function
	TypeError: a is not a function
	    at execute (/Users/luca.beurer-kellner/n4js-july-working/Eclipse.app/Contents/MacOS/workspace/TypeProject/src-gen/es/TypeProject/Test.js:28:5)
	Error loading TypeProject/Test
```

Upon using the `apply` function instead of the call-operator, another failure occurs:

```
class A extends Function {}

var a : Function = new A();
a.apply(a, undefined);
```

```
(SystemJS) Function.prototype.apply was called on [object Object], which is a object and not a function
	TypeError: Function.prototype.apply was called on [object Object], which is a object and not a function
	    at execute (/Users/luca.beurer-kellner/n4js-july-working/Eclipse.app/Contents/MacOS/workspace/TypeProject/src-gen/es/TypeProject/Test.js:28:7)
	Error loading TypeProject/Test
```

In fact the ES2015 spec states in *7.2.3 IsCallable* that to be callable an object has to have an internal [[Call]] method, that is not inherited via the prototype chain.

**Comment by lbeurerkellner** [comment]
Depends on #178
