### ISSUE TITLE
NPE in DirtyStateSupport when running library manager

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#1083]
`org.eclipse.n4js.ui.wizard.dependencies.ExternalLibrariesWizard  - unhandled error while setting up dependencies`

Exception happens when running big button on the project with external dependencies, while having editors open. Since exception is in the dirty state of the editors, there is a workaround: run big button with closed editors.
Despite the workaround issue remains and should be fixed.

root cause
```
Root exception:
java.lang.NullPointerException
	at org.eclipse.n4js.ui.editor.N4JSDirtyStateEditorSupport.equalDescriptions(N4JSDirtyStateEditorSupport.java:195)
	at org.eclipse.n4js.ui.editor.N4JSDirtyStateEditorSupport.isSignificantChange(N4JSDirtyStateEditorSupport.java:165)
	at org.eclipse.n4js.ui.editor.N4JSDirtyStateEditorSupport.descriptionsChanged(N4JSDirtyStateEditorSupport.java:231)
	at org.eclipse.xtext.resource.impl.AbstractResourceDescriptionChangeEventSource.notifyListeners(AbstractResourceDescriptionChangeEventSource.java:52)
	at org.eclipse.xtext.ui.notification.StateChangeEventBroker.descriptionsChanged(StateChangeEventBroker.java:20)
	at org.eclipse.xtext.resource.impl.AbstractResourceDescriptionChangeEventSource.notifyListeners(AbstractResourceDescriptionChangeEventSource.java:52)
	at org.eclipse.xtext.builder.impl.DirtyStateAwareResourceDescriptions.globalDescriptionsChanged(DirtyStateAwareResourceDescriptions.java:98)
	at org.eclipse.xtext.builder.impl.DirtyStateAwareResourceDescriptions$GlobalStateListener.descriptionsChanged(DirtyStateAwareResourceDescriptions.java:114)
	at org.eclipse.xtext.resource.impl.AbstractResourceDescriptionChangeEventSource.notifyListeners(AbstractResourceDescriptionChangeEventSource.java:52)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:123)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder$BuildOperation.run(ExternalLibraryBuilder.java:476)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder$BuildOperation.access$3(ExternalLibraryBuilder.java:435)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder.doPerformOperation(ExternalLibraryBuilder.java:307)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder.build(ExternalLibraryBuilder.java:183)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder.build(ExternalLibraryBuilder.java:165)
	at org.eclipse.n4js.ui.external.EclipseExternalLibraryWorkspace.registerProjectsInternal(EclipseExternalLibraryWorkspace.java:308)
	at org.eclipse.n4js.ui.external.EclipseExternalLibraryWorkspace.registerProjects(EclipseExternalLibraryWorkspace.java:199)
	at org.eclipse.n4js.ui.external.EclipseExternalIndexSynchronizer.synchronizeIndex(EclipseExternalIndexSynchronizer.java:139)
	at org.eclipse.n4js.ui.external.EclipseExternalIndexSynchronizer.synchronizeNpms(EclipseExternalIndexSynchronizer.java:90)
	at org.eclipse.n4js.external.LibraryManager.installNPMsInternal(LibraryManager.java:262)
	at org.eclipse.n4js.external.LibraryManager.lambda$2(LibraryManager.java:222)
	at org.eclipse.n4js.external.LibraryManager.runWithWorkspaceLock(LibraryManager.java:658)
	at org.eclipse.n4js.external.LibraryManager.installNPMs(LibraryManager.java:222)
	at org.eclipse.n4js.ui.external.ExternalLibrariesActionsHelper.installNoUpdate(ExternalLibrariesActionsHelper.java:135)
	at org.eclipse.n4js.ui.wizard.dependencies.ExternalLibrariesInstallHelper.calculateAndInstallDependencies(ExternalLibrariesInstallHelper.java:78)
	at org.eclipse.n4js.ui.wizard.dependencies.RunnableInstallDependencies.run(RunnableInstallDependencies.java:88)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

full stack:
```
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:398)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:980)
	at org.eclipse.n4js.ui.wizard.dependencies.ExternalLibrariesWizard.performFinish(ExternalLibrariesWizard.java:72)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:778)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:417)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.n4js.ui.handler.LibrariesFixHandler.execute(LibrariesFixHandler.java:26)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.n4js.product.N4JSApplication.start(N4JSApplication.java:141)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: java.lang.NullPointerException
	at org.eclipse.n4js.ui.editor.N4JSDirtyStateEditorSupport.equalDescriptions(N4JSDirtyStateEditorSupport.java:195)
	at org.eclipse.n4js.ui.editor.N4JSDirtyStateEditorSupport.isSignificantChange(N4JSDirtyStateEditorSupport.java:165)
	at org.eclipse.n4js.ui.editor.N4JSDirtyStateEditorSupport.descriptionsChanged(N4JSDirtyStateEditorSupport.java:231)
	at org.eclipse.xtext.resource.impl.AbstractResourceDescriptionChangeEventSource.notifyListeners(AbstractResourceDescriptionChangeEventSource.java:52)
	at org.eclipse.xtext.ui.notification.StateChangeEventBroker.descriptionsChanged(StateChangeEventBroker.java:20)
	at org.eclipse.xtext.resource.impl.AbstractResourceDescriptionChangeEventSource.notifyListeners(AbstractResourceDescriptionChangeEventSource.java:52)
	at org.eclipse.xtext.builder.impl.DirtyStateAwareResourceDescriptions.globalDescriptionsChanged(DirtyStateAwareResourceDescriptions.java:98)
	at org.eclipse.xtext.builder.impl.DirtyStateAwareResourceDescriptions$GlobalStateListener.descriptionsChanged(DirtyStateAwareResourceDescriptions.java:114)
	at org.eclipse.xtext.resource.impl.AbstractResourceDescriptionChangeEventSource.notifyListeners(AbstractResourceDescriptionChangeEventSource.java:52)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:123)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder$BuildOperation.run(ExternalLibraryBuilder.java:476)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder$BuildOperation.access$3(ExternalLibraryBuilder.java:435)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder.doPerformOperation(ExternalLibraryBuilder.java:307)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder.build(ExternalLibraryBuilder.java:183)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder.build(ExternalLibraryBuilder.java:165)
	at org.eclipse.n4js.ui.external.EclipseExternalLibraryWorkspace.registerProjectsInternal(EclipseExternalLibraryWorkspace.java:308)
	at org.eclipse.n4js.ui.external.EclipseExternalLibraryWorkspace.registerProjects(EclipseExternalLibraryWorkspace.java:199)
	at org.eclipse.n4js.ui.external.EclipseExternalIndexSynchronizer.synchronizeIndex(EclipseExternalIndexSynchronizer.java:139)
	at org.eclipse.n4js.ui.external.EclipseExternalIndexSynchronizer.synchronizeNpms(EclipseExternalIndexSynchronizer.java:90)
	at org.eclipse.n4js.external.LibraryManager.installNPMsInternal(LibraryManager.java:262)
	at org.eclipse.n4js.external.LibraryManager.lambda$2(LibraryManager.java:222)
	at org.eclipse.n4js.external.LibraryManager.runWithWorkspaceLock(LibraryManager.java:658)
	at org.eclipse.n4js.external.LibraryManager.installNPMs(LibraryManager.java:222)
	at org.eclipse.n4js.ui.external.ExternalLibrariesActionsHelper.installNoUpdate(ExternalLibrariesActionsHelper.java:135)
	at org.eclipse.n4js.ui.wizard.dependencies.ExternalLibrariesInstallHelper.calculateAndInstallDependencies(ExternalLibrariesInstallHelper.java:78)
	at org.eclipse.n4js.ui.wizard.dependencies.RunnableInstallDependencies.run(RunnableInstallDependencies.java:88)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by lbeurerkellner** [comment]
Closing all open editors before running the "big button", can be used as a temporary workaround.
