### ISSUE TITLE
NullPointerException when running the Setup External Libraries Wizard

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#1190]
The N4JS IDE (Dec. 2 2018) I get a NullPointerException when running the Setup External Libraries Wizard (colleagues as well).

There is an old issue with the same title at #1046 -- but I assume it is a different issue now (at least the exception is thrown somewhere else.

*This is a blocker!*

```
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:401)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:977)
	at org.eclipse.n4js.ui.wizard.dependencies.ExternalLibrariesWizard.performFinish(ExternalLibrariesWizard.java:72)
    ...
Caused by: java.lang.NullPointerException
	at org.eclipse.xtext.builder.impl.ToBeBuiltComputer.doRemoveProject(ToBeBuiltComputer.java:203)
	at org.eclipse.xtext.builder.impl.ToBeBuiltComputer.removeProject(ToBeBuiltComputer.java:180)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder$BuildOperation$2.getToBeBuilt(ExternalLibraryBuilder.java:464)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder$BuildOperation.run(ExternalLibraryBuilder.java:513)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder$BuildOperation.access$3(ExternalLibraryBuilder.java:495)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder.doPerformOperation(ExternalLibraryBuilder.java:341)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder.clean(ExternalLibraryBuilder.java:290)
	at org.eclipse.n4js.ui.external.ExternalLibraryBuilder.clean(ExternalLibraryBuilder.java:271)
	at org.eclipse.n4js.ui.external.EclipseExternalLibraryWorkspace.deregisterProjectsInternal(EclipseExternalLibraryWorkspace.java:270)
	at org.eclipse.n4js.ui.external.EclipseExternalLibraryWorkspace.deregisterAllProjects(EclipseExternalLibraryWorkspace.java:251)
	at org.eclipse.n4js.external.LibraryManager.installNPMsInternal(LibraryManager.java:223)
	at org.eclipse.n4js.external.LibraryManager.lambda$2(LibraryManager.java:189)
	at org.eclipse.n4js.external.LibraryManager$$Lambda$575/2131086871.get(Unknown Source)
	at org.eclipse.n4js.external.LibraryManager.runWithWorkspaceLock(LibraryManager.java:528)
	at org.eclipse.n4js.external.LibraryManager.installNPMs(LibraryManager.java:189)
	at org.eclipse.n4js.ui.external.ExternalLibrariesActionsHelper.cleanAndInstallAllDependencies(ExternalLibrariesActionsHelper.java:82)
	at org.eclipse.n4js.ui.wizard.dependencies.RunnableInstallDependencies.run(RunnableInstallDependencies.java:88)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by jpilgrim** [comment]
Findings:

1. IMHO `ExternalLibraryBuilder.BuildOperation.CLEAN.{...}.getToBeBuilt(ToBeBuiltComputer, N4JSEclipseProject, IProgressMonitor, IToBeBuiltComputerContribution)` is conceptually wrong: The projects to be cleaned are external projects by definition. That is, the location of the project is _outside_ the Eclispe workspace. That means resolving a file of that project in the Eclipse workspace _must_ fail. This is what we see in `org.eclipse.xtext.builder.impl.ToBeBuiltComputer.doRemoveProject(IProject, IProgressMonitor)`: The resolved storage is null, leading to the NPE in line 203. 
The IDE fails for the first external library. But after catching the exception it became clear that it fails for _every_ external library. This confirms my suspicion.
2. The `CLEAN` operation is called twice for the same projects -- why is that? It is called two times: 
	a. `LibraryManager.installNPMsInternal(Map<String, NPMVersionRequirement>, boolean, IProgressMonitor)`, line 223
	b. `LibraryManager.installNPMsInternal(Map<String, NPMVersionRequirement>, boolean, IProgressMonitor)`, line 229	

Independently of a bug in n4js I would say that `ToBeBuiltComputer.doRemoveProject` is buggy as well: It might very well happen that a URI of a resource (from the description) cannot be resolved anymore. I think this method must be made more robust.

In any case I would like to have much better documentation available.

Made slight adjustments on branch GH-1046 (which is the wrong branch name, sorry, I mixed up the issue ID with the old report).

**Comment by mor-n4** [comment]
Seems to be caused by the following new behavior in Xtext:
https://github.com/eclipse/xtext-eclipse/blame/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperImpl.java#L223-L234

I'll provide a quick fix.

Not sure yet how to solve this properly. It seems that there is a clash between Eclipse's/Xtext's interpretation of file URIs and the use of file URIs in our external library manager. My best guess is a full-blown solution would require to introduce a proper URI scheme for the external library workspace to cleanly differentiate between the cases (i.e. URIs denoting a file in the external workspace and URIs denoting files outside any workspace, somewhere on the user's disk).

**Comment by mor-n4** [comment]
PENDING: think about adding a test!

**Comment by mor-n4** [comment]
Created #1198 (discovery user story) for further investigating this.
