### ISSUE TITLE
Some tests throwing exceptions in maven build but not reported as failing

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1201]
During the maven build, some tests throw exceptions but are not reported as failed by Jenkins et al.

A good search string for finding them in the log is `JSONModelUtils.java:539`. Look for this in any green Jenkins build (e.g. nightly, CI). But also check some other search strings.

Sample stack trace (note the message "Tests run: 0, Failures: 0, Errors: 0, Skipped: 0" at the end):
```
00:52:46.311 2018-12-351-11:19:53.053+0100 -            Framework stop - ERROR - ResourceServiceProviderDescriptor - (org.eclipse.xtext.internal.ResourceServiceProviderDescriptor.java:48) - Could not create the Injector for org.eclipse.n4js.json.ui.JSONExecutableExtensionFactory.
00:52:46.311 Bundle org.eclipse.n4js.json.ui was not activated.
00:52:46.311 Please check that all dependencies could be resolved and 'Bundle-ActivationPolicy: lazy' is configured in the bundle's MANIFEST.MF. Check also the error log.
00:52:46.311 org.eclipse.core.runtime.CoreException: Could not create the Injector for org.eclipse.n4js.json.ui.JSONExecutableExtensionFactory.
00:52:46.311 Bundle org.eclipse.n4js.json.ui was not activated.
00:52:46.312 Please check that all dependencies could be resolved and 'Bundle-ActivationPolicy: lazy' is configured in the bundle's MANIFEST.MF. Check also the error log.
00:52:46.312 	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.handleCreationError(AbstractGuiceAwareExecutableExtensionFactory.java:96)
00:52:46.312 	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:55)
00:52:46.312 	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:265)
00:52:46.312 	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
00:52:46.312 	at org.eclipse.xtext.internal.ResourceServiceProviderDescriptor.getExtension(ResourceServiceProviderDescriptor.java:46)
00:52:46.312 	at org.eclipse.xtext.internal.AbstractResourceServiceProviderDescriptor.get(AbstractResourceServiceProviderDescriptor.java:20)
00:52:46.312 	at org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl$InternalData.getServiceProvider(ResourceServiceProviderRegistryImpl.java:46)
00:52:46.312 	at org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl.getResourceServiceProvider(ResourceServiceProviderRegistryImpl.java:109)
00:52:46.312 	at org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl.getResourceServiceProvider(ResourceServiceProviderRegistryImpl.java:129)
00:52:46.312 	at org.eclipse.n4js.utils.languages.N4LanguageUtils.getServiceForContext(N4LanguageUtils.java:157)
00:52:46.312 	at org.eclipse.n4js.utils.languages.N4LanguageUtils.getServiceForContext(N4LanguageUtils.java:135)
00:52:46.312 	at org.eclipse.n4js.json.model.utils.JSONModelUtils.serializeJSON(JSONModelUtils.java:539)
00:52:46.312 	at org.eclipse.n4js.json.model.utils.JSONModelUtils.serializeJSON(JSONModelUtils.java:532)
00:52:46.312 	at org.eclipse.n4js.ui.workingsets.ManualAssociationAwareWorkingSetManager.projectAssociationsToJsonString(ManualAssociationAwareWorkingSetManager.java:146)
00:52:46.312 	at org.eclipse.n4js.ui.workingsets.ManualAssociationAwareWorkingSetManager.saveState(ManualAssociationAwareWorkingSetManager.java:96)
00:52:46.312 	at org.eclipse.n4js.ui.workingsets.WorkingSetManagerBrokerImpl.saveState(WorkingSetManagerBrokerImpl.java:139)
00:52:46.312 	at org.eclipse.n4js.ui.workingsets.WorkingSetManagerBrokerImpl$1.saving(WorkingSetManagerBrokerImpl.java:124)
00:52:46.312 	at org.eclipse.core.internal.resources.SaveManager.executeLifecycle(SaveManager.java:384)
00:52:46.312 	at org.eclipse.core.internal.resources.SaveManager$1.run(SaveManager.java:201)
00:52:46.312 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
00:52:46.312 	at org.eclipse.core.internal.resources.SaveManager.broadcastLifecycle(SaveManager.java:204)
00:52:46.312 	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1169)
00:52:46.312 	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1148)
00:52:46.312 	at org.eclipse.core.internal.resources.DelayedSnapshotJob.run(DelayedSnapshotJob.java:55)
00:52:46.312 	at org.eclipse.core.internal.resources.SaveManager.shutdown(SaveManager.java:1423)
00:52:46.312 	at org.eclipse.core.internal.resources.Workspace.close(Workspace.java:610)
00:52:46.313 	at org.eclipse.core.resources.ResourcesPlugin.stop(ResourcesPlugin.java:459)
00:52:46.313 	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:838)
00:52:46.313 	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
00:52:46.313 	at java.security.AccessController.doPrivileged(Native Method)
00:52:46.313 	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:831)
00:52:46.313 	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1019)
00:52:46.313 	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:362)
00:52:46.313 	at org.eclipse.osgi.container.Module.doStop(Module.java:639)
00:52:46.313 	at org.eclipse.osgi.container.Module.stop(Module.java:501)
00:52:46.313 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1726)
00:52:46.313 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1645)
00:52:46.313 	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:273)
00:52:46.313 	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:195)
00:52:46.313 	at org.eclipse.osgi.container.Module.doStop(Module.java:639)
00:52:46.313 	at org.eclipse.osgi.container.Module.stop(Module.java:501)
00:52:46.313 	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:205)
00:52:46.313 	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:213)
00:52:46.313 	at java.lang.Thread.run(Thread.java:748)

<-------- omitting several almost identical stack traces -------->

00:52:46.318 !ENTRY org.eclipse.core.resources 4 2 2018-12-17 11:19:53.106
00:52:46.318 !MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
00:52:46.318 !STACK 0
00:52:46.318 java.util.NoSuchElementException: No value present
00:52:46.318 	at java.util.Optional.get(Optional.java:135)
00:52:46.318 	at org.eclipse.n4js.json.model.utils.JSONModelUtils.serializeJSON(JSONModelUtils.java:539)
00:52:46.318 	at org.eclipse.n4js.json.model.utils.JSONModelUtils.serializeJSON(JSONModelUtils.java:532)
00:52:46.319 	at org.eclipse.n4js.ui.workingsets.ManualAssociationAwareWorkingSetManager.projectAssociationsToJsonString(ManualAssociationAwareWorkingSetManager.java:146)
00:52:46.319 	at org.eclipse.n4js.ui.workingsets.ManualAssociationAwareWorkingSetManager.saveState(ManualAssociationAwareWorkingSetManager.java:96)
00:52:46.319 	at org.eclipse.n4js.ui.workingsets.WorkingSetManagerBrokerImpl.saveState(WorkingSetManagerBrokerImpl.java:139)
00:52:46.319 	at org.eclipse.n4js.ui.workingsets.WorkingSetManagerBrokerImpl$1.saving(WorkingSetManagerBrokerImpl.java:124)
00:52:46.319 	at org.eclipse.core.internal.resources.SaveManager.executeLifecycle(SaveManager.java:384)
00:52:46.319 	at org.eclipse.core.internal.resources.SaveManager$1.run(SaveManager.java:201)
00:52:46.319 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
00:52:46.319 	at org.eclipse.core.internal.resources.SaveManager.broadcastLifecycle(SaveManager.java:204)
00:52:46.319 	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1169)
00:52:46.319 	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1148)
00:52:46.319 	at org.eclipse.core.internal.resources.DelayedSnapshotJob.run(DelayedSnapshotJob.java:55)
00:52:46.319 	at org.eclipse.core.internal.resources.SaveManager.shutdown(SaveManager.java:1423)
00:52:46.319 	at org.eclipse.core.internal.resources.Workspace.close(Workspace.java:610)
00:52:46.319 	at org.eclipse.core.resources.ResourcesPlugin.stop(ResourcesPlugin.java:459)
00:52:46.319 	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:838)
00:52:46.319 	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
00:52:46.319 	at java.security.AccessController.doPrivileged(Native Method)
00:52:46.319 	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:831)
00:52:46.319 	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1019)
00:52:46.319 	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:362)
00:52:46.319 	at org.eclipse.osgi.container.Module.doStop(Module.java:639)
00:52:46.319 	at org.eclipse.osgi.container.Module.stop(Module.java:501)
00:52:46.319 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1726)
00:52:46.319 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1645)
00:52:46.319 	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:273)
00:52:46.319 	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:195)
00:52:46.319 	at org.eclipse.osgi.container.Module.doStop(Module.java:639)
00:52:46.319 	at org.eclipse.osgi.container.Module.stop(Module.java:501)
00:52:46.319 	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:205)
00:52:46.319 	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:213)
00:52:46.320 	at java.lang.Thread.run(Thread.java:748)
00:52:46.320 
00:52:46.320 !ENTRY org.eclipse.core.resources 2 10035 2018-12-17 11:19:53.109
00:52:46.320 !MESSAGE The workspace will exit with unsaved changes in this session.
00:53:04.400 
00:53:04.400 Results :
00:53:04.400 
00:53:04.400 Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by mor-n4** [comment]
Some first changes can be found on branch `GH-1201`.

**Comment by mor-n4** [comment]
Could not reproduce this as of 2019-05-23. Closing as invalid.
