### ISSUE TITLE
N4JS Oomph Setup fails with SSL handshake_failure

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#1212]
I was just trying to setup a fresh development environment using the Eclipse Installer.

I am using Oxygen, Eclipse IDE for Committers and the "Eclipse Projects > N4JS" project.

Right after initiating the setup, I run into a SSL handshake_failure with the update site of xpect (https://ci.eclipse.org/xpect/job/Xpect-Integration-Release/lastSuccessfulBuild/artifact/org.eclipse.xpect.releng/p2-repository/target/repository/content.xml).

Can this be reproduced on your end as well?

```
ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 Unable to read repository at https://ci.eclipse.org/xpect/job/Xpect-Integration-Release/lastSuccessfulBuild/artifact/org.eclipse.xpect.releng/p2-repository/target/repository/content.xml.
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
  at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
  at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
  at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
  at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
  at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
  at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:553)
  at org.eclipse.ecf.provider.filetransfer.httpclient4.SNIAwareHttpClient$1.connectSocket(SNIAwareHttpClient.java:64)
  at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
  at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
  at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
  at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
  at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
  at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:263)
  at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

@team I hope you're all doing well! Keep up the good work.

**Comment by qtran-n4** [comment]
@lbeurerkellner Thanks for the issue. What's up bro? :)

**Comment by qtran-n4** [comment]
@lbeurerkellner Please provide information about: 
- OS
- Java version
- etc.

**Comment by jpilgrim** [comment]
I tried to oomph the Ecipse N4JS workspace on a VM with a fresh Ubuntu (no cache etc. available) and it worked (I only had to set the n4js git URL to use https...).

I also checked the certificate of ci.eclipse.org which looks fine.

So I'm closing this issue. I assume you have to simply try again.
