### ISSUE TITLE
Tests failing due to different logging formats

### ISSUE THREAD

**Issue by rodrigoehlers** [eclipse/n4js#1498]
While running all tests in `org.eclipse.n4js.spec.tests`, 3 failed with the following failure trace.

Operating System: macOS Catalina Version 10.15 (Beta 8)
Node.js Version: 12.6.0

1. AnnotationsInfo.n4js.xt (output~0)
```
org.junit.ComparisonFailure: expected:<.../* XPECT output ---
[<==
stdout:
class annotations
# extract of all annotations
 =annotations : 
  - name:  Ignore
    value : because of reasons
  - name:  Group
    value : UT
  - name:  Group
    value : IT
# has annotation Group true
# has annotation Observable false
# any annotations with name Observable null
# any annotations with name Group N4Annotation { name: 'Group', details: [ 'IT' ] }
# all annotations with name Ignore [ N4Annotation { name: 'Ignore', details: [ 'because of reasons' ] } ]
# all annotations with name Group [ N4Annotation { name: 'Group', details: [ 'UT' ] },
  N4Annotation { name: 'Group', details: [ 'IT' ] } ]]
# all annotations ...> but was:<.../* XPECT output ---
[======================================================================
Kind information from OutputXpectMethod:
following output was produced using generator options "ES5plus"
======================================================================
<==
stdout:
class annotations
# extract of all annotations
 =annotations : 
  - name:  Ignore
    value : because of reasons
  - name:  Group
    value : UT
  - name:  Group
    value : IT
# has annotation Group true
# has annotation Observable false
# any annotations with name Observable null
# any annotations with name Group N4Annotation { name: 'Group', details: [ 'IT' ] }
# all annotations with name Ignore [ N4Annotation { name: 'Ignore', details: [ 'because of reasons' ] } ]
# all annotations with name Group [
  N4Annotation { name: 'Group', details: [ 'UT' ] },
  N4Annotation { name: 'Group', details: [ 'IT' ] }
]]
# all annotations ...>
	at org.eclipse.xpect.expectation.impl.StringExpectationImpl.assertEquals(StringExpectationImpl.java:60)
	at org.eclipse.n4js.xpect.ui.methods.OutputXpectMethod.lambda$0(OutputXpectMethod.java:87)
	at org.eclipse.n4js.xpect.ui.methods.OutputXpectMethod.runWithDefaultConfigs(OutputXpectMethod.java:231)
	at org.eclipse.n4js.xpect.ui.methods.OutputXpectMethod.output(OutputXpectMethod.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.xpect.runner.TestExecutor.runTest(TestExecutor.java:161)
	at org.eclipse.xpect.runner.XpectTestRunner.runInternal(XpectTestRunner.java:71)
	at org.eclipse.xpect.runner.AbstractTestRunner.run(AbstractTestRunner.java:63)
	at org.eclipse.xpect.runner.XpectFileRunner.run(XpectFileRunner.java:146)
	at org.eclipse.xpect.runner.XpectRunner.runChild(XpectRunner.java:212)
	at org.eclipse.xpect.runner.XpectRunner.runChild(XpectRunner.java:1)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.xpect.runner.XpectRunner.run(XpectRunner.java:198)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

2. ReflectionEnum.n4js.xt (output~0)
```
org.junit.ComparisonFailure: expected:<.../* XPECT output ---
[<==
stdout:
Ch07_04_Reflection_Meta_Information.ReflectionEnum.E
Ch07_04_Reflection_Meta_Information.ReflectionEnum.E
true
[ E { name: 'L1', value: 'l1' },
  E { name: 'L2', value: 'L2' },
  E { name: 'L3', value: 'L3' } ]]
stderr:
==>
--- */...> but was:<.../* XPECT output ---
[======================================================================
Kind information from OutputXpectMethod:
following output was produced using generator options "ES5plus"
======================================================================
<==
stdout:
Ch07_04_Reflection_Meta_Information.ReflectionEnum.E
Ch07_04_Reflection_Meta_Information.ReflectionEnum.E
true
[
  E { name: 'L1', value: 'l1' },
  E { name: 'L2', value: 'L2' },
  E { name: 'L3', value: 'L3' }
]]
stderr:
==>
--- */...>
	at org.eclipse.xpect.expectation.impl.StringExpectationImpl.assertEquals(StringExpectationImpl.java:60)
	at org.eclipse.n4js.xpect.ui.methods.OutputXpectMethod.lambda$0(OutputXpectMethod.java:87)
	at org.eclipse.n4js.xpect.ui.methods.OutputXpectMethod.runWithDefaultConfigs(OutputXpectMethod.java:231)
	at org.eclipse.n4js.xpect.ui.methods.OutputXpectMethod.output(OutputXpectMethod.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.xpect.runner.TestExecutor.runTest(TestExecutor.java:161)
	at org.eclipse.xpect.runner.XpectTestRunner.runInternal(XpectTestRunner.java:71)
	at org.eclipse.xpect.runner.AbstractTestRunner.run(AbstractTestRunner.java:63)
	at org.eclipse.xpect.runner.XpectFileRunner.run(XpectFileRunner.java:146)
	at org.eclipse.xpect.runner.XpectRunner.runChild(XpectRunner.java:212)
	at org.eclipse.xpect.runner.XpectRunner.runChild(XpectRunner.java:1)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.xpect.runner.XpectRunner.run(XpectRunner.java:198)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

3. Promisify_useCases.n4js.xt (output~0)
```
org.junit.ComparisonFailure: expected:<.../* XPECT output ---
[<==
stdout:
starting ...

****************** using promisifiable function:
use case #1: with await, long syntax
-> res01: hello from foo!
use case #2: with await, short syntax
-> res02: hello from foo!
use case #3: use Promise directly
-> res03: hello from foo!
use case #4: pass in a callback (don't use promisify at all)
-> callback got res04: hello from foo!

****************** using promisifiable method (non-static):
****** method mOne:
use case #1: with await, long syntax
-> res11: hello from C#mOne! (value of field: valueOfField)
use case #2: with await, short syntax
-> res12: hello from C#mOne! (value of field: valueOfField)
****** method mMany:
use case #1: with await, long syntax
-> res21: [ 'hello from C#mMany! (value of field: valueOfField)',
  42,
  { prop: 'value' } ]
use case #2: with await, short syntax
-> res22: [ 'hello from C#mMany! (value of field: valueOfField)',
  42,
  { prop: 'value' } ]
****** method mNone:
use case #1: with await, long syntax
-> res31: undefined
use case #2: with await, short syntax
-> res32: undefined
****** method mOneNoErr:
use case #1: with await, long syntax
-> res41: hello from C#mOneNoErr! (value of field: valueOfField)
use case #2: with await, short syntax
-> res42: hello from C#mOneNoErr! (value of field: valueOfField)
****** method mManyNoErr:
use case #1: with await, long syntax
-> res51: [ 'hello from C#mManyNoErr! (value of field: valueOfField)',
  42,
  { prop: 'value' } ]
use case #2: with await, short syntax
-> res52: [ 'hello from C#mManyNoErr! (value of field: valueOfField)',
  42,
  { prop: 'value' } ]]
****** method mNon...> but was:<.../* XPECT output ---
[======================================================================
Kind information from OutputXpectMethod:
following output was produced using generator options "ES5plus"
======================================================================
<==
stdout:
starting ...

****************** using promisifiable function:
use case #1: with await, long syntax
-> res01: hello from foo!
use case #2: with await, short syntax
-> res02: hello from foo!
use case #3: use Promise directly
-> res03: hello from foo!
use case #4: pass in a callback (don't use promisify at all)
-> callback got res04: hello from foo!

****************** using promisifiable method (non-static):
****** method mOne:
use case #1: with await, long syntax
-> res11: hello from C#mOne! (value of field: valueOfField)
use case #2: with await, short syntax
-> res12: hello from C#mOne! (value of field: valueOfField)
****** method mMany:
use case #1: with await, long syntax
-> res21: [
  'hello from C#mMany! (value of field: valueOfField)',
  42,
  { prop: 'value' }
]
use case #2: with await, short syntax
-> res22: [
  'hello from C#mMany! (value of field: valueOfField)',
  42,
  { prop: 'value' }
]
****** method mNone:
use case #1: with await, long syntax
-> res31: undefined
use case #2: with await, short syntax
-> res32: undefined
****** method mOneNoErr:
use case #1: with await, long syntax
-> res41: hello from C#mOneNoErr! (value of field: valueOfField)
use case #2: with await, short syntax
-> res42: hello from C#mOneNoErr! (value of field: valueOfField)
****** method mManyNoErr:
use case #1: with await, long syntax
-> res51: [
  'hello from C#mManyNoErr! (value of field: valueOfField)',
  42,
  { prop: 'value' }
]
use case #2: with await, short syntax
-> res52: [
  'hello from C#mManyNoErr! (value of field: valueOfField)',
  42,
  { prop: 'value' }
]]
****** method mNon...>
	at org.eclipse.xpect.expectation.impl.StringExpectationImpl.assertEquals(StringExpectationImpl.java:60)
	at org.eclipse.n4js.xpect.ui.methods.OutputXpectMethod.lambda$0(OutputXpectMethod.java:87)
	at org.eclipse.n4js.xpect.ui.methods.OutputXpectMethod.runWithDefaultConfigs(OutputXpectMethod.java:231)
	at org.eclipse.n4js.xpect.ui.methods.OutputXpectMethod.output(OutputXpectMethod.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.xpect.runner.TestExecutor.runTest(TestExecutor.java:161)
	at org.eclipse.xpect.runner.XpectTestRunner.runInternal(XpectTestRunner.java:71)
	at org.eclipse.xpect.runner.AbstractTestRunner.run(AbstractTestRunner.java:63)
	at org.eclipse.xpect.runner.XpectFileRunner.run(XpectFileRunner.java:146)
	at org.eclipse.xpect.runner.XpectRunner.runChild(XpectRunner.java:212)
	at org.eclipse.xpect.runner.XpectRunner.runChild(XpectRunner.java:1)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.xpect.runner.XpectRunner.run(XpectRunner.java:198)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

Tests need to be changed to verify content before it's logged and formatted in a specific way.

**Comment by mmews-n4** [comment]
@rodrigoehlers Thank you for your report. Right, the reason for this error is the version of node.js you are using compared to the version we are using.

**node.js v10.13**
```
# all annotations with name Group [ N4Annotation { name: 'Group', details: [ 'UT' ] },
  N4Annotation { name: 'Group', details: [ 'IT' ] } ]]
```

**node.js v12.6**
```
# all annotations with name Group [
  N4Annotation { name: 'Group', details: [ 'UT' ] },
  N4Annotation { name: 'Group', details: [ 'IT' ] }
]]
```

To solve this, either the node.js version should be checked or the string comparison should ignore whitespaces.

**Comment by jpilgrim** [comment]
Thank you, Marcus, for that hint. In order to get that task done, we will

1. try to write a new Xpect output tests which ignores whitespaces, based on the original output test. This is time framed, we do not want to spent more than 1 day on that.
2. if 1. works -- great. Otherwise we will re-write the three tests in the JavaScript code in order to not rely on the node.js formatting.

**Comment by jpilgrim** [comment]
Assigned to Rodrigo, Eduard and Thanh (HAW Project).
