### ISSUE TITLE
NPE in build (maybe caused by parallelization)

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1618]
When building Stdlib, the following exception was thrown (current master is 9b6b098):

**Stacktrace**
```

Caused by: java.lang.NullPointerException
	at org.eclipse.n4js.resource.N4JSResource.doResolveProxy(N4JSResource.java:1070)
	at org.eclipse.n4js.utils.emf.ProxyResolvingEObjectImpl.eResolveProxy(ProxyResolvingEObjectImpl.java:32)
	at org.eclipse.n4js.ts.typeRefs.impl.ParameterizedTypeRefImpl.getDeclaredType(ParameterizedTypeRefImpl.java:207)
	at org.eclipse.n4js.typesystem.SubstTypeVariablesJudgment$SubstTypeVariablesSwitch.caseParameterizedTypeRef(SubstTypeVariablesJudgment.java:381)
	at org.eclipse.n4js.typesystem.SubstTypeVariablesJudgment$SubstTypeVariablesSwitch.caseParameterizedTypeRef(SubstTypeVariablesJudgment.java:1)
	at org.eclipse.n4js.ts.typeRefs.util.TypeRefsSwitch.doSwitch(TypeRefsSwitch.java:193)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.n4js.typesystem.SubstTypeVariablesJudgment$SubstTypeVariablesSwitch.substTypeVariables(SubstTypeVariablesJudgment.java:100)
	at org.eclipse.n4js.typesystem.SubstTypeVariablesJudgment$SubstTypeVariablesSwitch.substTypeVariables(SubstTypeVariablesJudgment.java:94)
	at org.eclipse.n4js.typesystem.SubstTypeVariablesJudgment$SubstTypeVariablesSwitch.caseComposedTypeRef(SubstTypeVariablesJudgment.java:343)
	at org.eclipse.n4js.typesystem.SubstTypeVariablesJudgment$SubstTypeVariablesSwitch.caseComposedTypeRef(SubstTypeVariablesJudgment.java:1)
	at org.eclipse.n4js.ts.typeRefs.util.TypeRefsSwitch.doSwitch(TypeRefsSwitch.java:134)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.n4js.typesystem.SubstTypeVariablesJudgment.apply(SubstTypeVariablesJudgment.java:62)
	at org.eclipse.n4js.typesystem.N4JSTypeSystem.substTypeVariables(N4JSTypeSystem.java:314)
	at org.eclipse.n4js.typesystem.N4JSTypeSystem.substTypeVariables(N4JSTypeSystem.java:289)
	at org.eclipse.n4js.validation.AbstractN4JSDeclarativeValidator.internalCheckTypeArguments(AbstractN4JSDeclarativeValidator.java:308)
	at org.eclipse.n4js.validation.validators.N4JSTypeValidator.checkParameterizedTypeRef(N4JSTypeValidator.java:205)
	at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:127)
	at org.eclipse.n4js.validation.N4JSValidator$N4JSMethodWrapperCancelable.invoke(N4JSValidator.java:112)
	... 37 more```

**Comment by szarnekow** [comment]
Is this reproducible for you, @mmews-n4 ?

**Comment by mmews-n4** [comment]
I just checked and could not reproduce it; I'll close it.
Thanks for noting!
