### ISSUE TITLE
Some tests in bundle org.eclipse.n4js.ide.tests are not executed on Jenkins

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1734]
Some of the tests in bundle `org.eclipse.n4js.ide.tests` are not executed on Jenkins.

For one of those tests there exists another ticket (see #1392) and that test is not working properly anyway. Fixing that test is not part of this ticket (just set it on ignore), it must be investigated why that test and others are not running on Jenkins and that must be fixed.

**Comment by mor-n4** [comment]
NOTE: this is not done yet. One test is on ignore (search for `GH-1734`).

**Comment by mor-n4** [comment]
Probably related:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 8 out of bounds for object array[7]
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.eclipse.emf.common.util.BasicEList.grow(BasicEList.java:729)
	at org.eclipse.emf.common.util.BasicEList.addUnique(BasicEList.java:415)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:304)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl$EAdapterList.add(BasicNotifierImpl.java:224)
	at org.eclipse.n4js.resource.PostProcessingEntryTracker.lambda$0(PostProcessingEntryTracker.java:55)
```

**Comment by szarnekow** [comment]
When running org.eclipse.n4js.ide.tests.RuntimeDependencyValidationIdeTest locally, I see a consistent single failure on `testLoadtimeDependencyConflict()`
```
java.lang.AssertionError: issues in module test-workspace/test-project/src/C.n4js do not meet expectation
EXPECTED:
(Error, [0:16 - 0:19], A load-time dependency target module B must only be imported once within the same runtime dependency cycle, but B is also imported by module X.
    Containing runtime dependency cycle cluster:
        *A.n4js --> Y.n4js
        *B.n4js --> A.n4js
        C.n4js --> B.n4js
        X.n4js --> B.n4js, C.n4js
        Y.n4js --> X.n4js)
ACTUAL:
    <none>
	at org.junit.Assert.fail(Assert.java:88)
	at org.eclipse.n4js.ide.tests.server.AbstractIdeTest.assertIssuesInModules(AbstractIdeTest.java:729)
	at org.eclipse.n4js.ide.tests.server.AbstractIdeTest.assertIssuesInModules(AbstractIdeTest.java:700)
	at org.eclipse.n4js.ide.tests.server.AbstractIdeTest.assertIssuesInModules(AbstractIdeTest.java:692)
	at org.eclipse.n4js.ide.tests.RuntimeDependencyValidationIdeTest.testLoadtimeDependencyConflict(RuntimeDependencyValidationIdeTest.java:273)
```

**Comment by mor-n4** [comment]
The last test that caused trouble (RuntimeDependencyValidationIdeTest) was due to a bug in the finalization of post processing.

However, it's interesting that this did not show in Eclipse editors and incremental builder. My guess is that the LSP server is reusing more EMF resources (and retaining them for a longer time) whereas in the Eclipse case EMF resources are built from scratch, most of the time.

If this should be investigated further sometime in the future, a starting point might be to revert PR #1760 and debug the failure(s) in RuntimeDependencyValidationIdeTest.

**Comment by mor-n4** [comment]
All newly enabled tests seem to work reliably now, both locally and on Jenkins. Closing this as fixed.
