### ISSUE TITLE
IndexOutOfBoundsException in content assist / FollowElementComputer

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1756]
After programming N4JS (in Eclipse) for a while I had several of the following stack trace in the Console view of the parent Eclipse instance:
```
2020-05-127-01:46:31.031+0200 -                      main - ERROR -    ContentAssistContextFactory - (org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.java:182) - java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.doCreateContexts(ContentAssistContextFactory.java:180)
	at org.eclipse.n4js.ide.editor.contentassist.N4JSContentAssistContextFactory.doCreateContexts(N4JSContentAssistContextFactory.java:40)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.create(ContentAssistContextFactory.java:130)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.DelegatingContentAssistContextFactory$StatefulFactory.doCreateContexts(DelegatingContentAssistContextFactory.java:92)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.DelegatingContentAssistContextFactory$StatefulFactory.create(DelegatingContentAssistContextFactory.java:78)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.DelegatingContentAssistContextFactory.create(DelegatingContentAssistContextFactory.java:55)
	at org.eclipse.n4js.ui.utils.ImportUtil.createContentAssistContexts(ImportUtil.java:158)
	at org.eclipse.n4js.ui.utils.ImportUtil.lambda$0(ImportUtil.java:145)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:524)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:496)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:135)
	at org.eclipse.n4js.ui.utils.ImportUtil.findImportCandidates(ImportUtil.java:153)
	at org.eclipse.n4js.ui.utils.ImportUtil.findImportCandidates(ImportUtil.java:129)
	at org.eclipse.n4js.ui.quickfix.N4JSQuickfixProvider.addImportForUnresolvedReference(N4JSQuickfixProvider.java:303)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.xtext.ui.editor.quickfix.AbstractDeclarativeQuickfixProvider.getResolutions(AbstractDeclarativeQuickfixProvider.java:57)
	at org.eclipse.xtext.ui.editor.quickfix.AbstractDeclarativeQuickfixProvider.getResolutions(AbstractDeclarativeQuickfixProvider.java:87)
	at org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider.getResolutions(DefaultQuickfixProvider.java:246)
	at org.eclipse.xtext.ui.editor.quickfix.AbstractIssueResolutionProviderAdapter.getResolutions(AbstractIssueResolutionProviderAdapter.java:46)
	at org.eclipse.xtext.ui.editor.quickfix.XtextQuickAssistProcessor.createQuickfixes(XtextQuickAssistProcessor.java:154)
	at org.eclipse.xtext.ui.editor.quickfix.XtextQuickAssistProcessor.computeQuickAssistProposals(XtextQuickAssistProcessor.java:123)
	at org.eclipse.xtext.ui.editor.hover.AnnotationWithQuickFixesHover$CompletionProposalRunnable.run(AnnotationWithQuickFixesHover.java:604)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3812)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.n4js.product.N4JSApplication.start(N4JSApplication.java:141)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.setParamConfigAndUpdateOffset(FollowElementComputer.java:174)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:99)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:164)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:85)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:75)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:80)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.doCreateContexts(ContentAssistContextFactory.java:318)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.PartialContentAssistContextFactory.handleLastCompleteNodeAsPartOfDatatypeNode(PartialContentAssistContextFactory.java:53)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory$1.call(ContentAssistContextFactory.java:148)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory$1.call(ContentAssistContextFactory.java:145)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mor-n4** [comment]
To reproduce trigger content assist after `someFun`:
```javascript
let value;

export function foo(): any {
    return (arg) => {
        let x = async () => {
            value = new C((p: Object) => {
            	someFun/* <-- here! */
            });
            return null;
        };
	}
}

class C {
	constructor(f: Function) {}
}

function someFunctionWithAnExtremelyLooooongName() {}
```
(tested only in Eclipse)
