### ISSUE TITLE
Quick Access Search breaks and yields NPEs when proxied editor tabs appear in results

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#177]
When closing and re-opening an N4JS IDE with multiple open editor tabs, only the first editor tab seems to be loaded:

![image](https://user-images.githubusercontent.com/17903049/29675221-d65bf760-88f4-11e7-8363-32ee08881470.png)
(visible due to missing editor icon for A.n4js in contrast to the active editor for B.n4js)

This on its own might already be considered a bug. However, when using the quick access search in the top right corner of the IDE (Cmd-3 on macOS) this can provoke NPEs that are logged on the console. Just type any character that appears in the title of one of the inactive (proxied) editor tabs. In my example that would be `A.n4js`. 

This results in the following exception on the console:

```
java.lang.NullPointerException
	at org.eclipse.jface.resource.ImageDataImageDescriptor.<init>(ImageDataImageDescriptor.java:36)
	at org.eclipse.jface.resource.ImageDescriptor.createFromImage(ImageDescriptor.java:104)
	at org.eclipse.ui.internal.quickaccess.EditorElement.getImageDescriptor(EditorElement.java:56)
	at org.eclipse.ui.internal.quickaccess.QuickAccessEntry.getImage(QuickAccessEntry.java:115)
	at org.eclipse.ui.internal.quickaccess.QuickAccessEntry.paint(QuickAccessEntry.java:218)
	at org.eclipse.ui.internal.quickaccess.QuickAccessContents$9.handleEvent(QuickAccessContents.java:767)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Table.drawInteriorWithFrame_inView(Table.java:1176)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5978)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:758)
	at org.eclipse.swt.widgets.Table.drawRect(Table.java:1193)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5711)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5084)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5465)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:94)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.n4js.product.N4JSApplication.start(N4JSApplication.java:141)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

Also, the quick access search itself breaks by not showing any results for that query:

![image](https://user-images.githubusercontent.com/17903049/29675449-7b4ff050-88f5-11e7-9504-3e1550112800.png)

**Comment by qtran-n4** [comment]
Fixed
