### ISSUE TITLE
LSP builder throwing exception after file was renamed/deleted

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1789]
When a file is being renamed or deleted in VSCode, no `didChangeWatchedFiles` notification is sent by VSCode to the LSP server. During the next build, e.g. triggered by the user through saving an open editor, the LSP builder throws an exception, because it still expects the renamed/deleted file to exist under the original name.

The fact that no `didChangeWatchedFiles` is sent might be caused by an incorrect configuration sent from the server to VSCode during server initialization, which might be easiy to fix. However, the builder should still be able to deal with "missing" files gracefully (treating them as deleted), because

1. we cannot be sure that all LSP clients will send `didChangeWatchedFiles` correctly,
2. the above situation can happen even if `didChangeWatchedFiles` notifcations are sent: if a build is in progress while the file is renamed/deleted, the `didChangeWatchedFiles` notifcation will not be noticed by the running build, only by the next build following that.

To reproduce:
* create a file `Main.n4js` exporting a class with a method,
* create a second file `A01.n4js` importing and using the class,
* close file `A01.n4js` and build the workspace,
* rename or delete file `A01.n4js` in VSCode without opening it,
* change the method name in `Main.n4js` and save
  --> will lead to an exception because `A01.n4js` cannot be loaded by EMF:
```
1    [pool-2-thread-2] ERROR erver.concurrent.LSPExecutorService  - error during queued task: 
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /Users/mark-oliver.reiser/Desktop/temp-n4js-test/singleProject/ProjectA/src/A01.n4js (No such file or directory)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$ResourceLocator.demandLoadHelper(ResourceSetImpl.java:804)
	at org.eclipse.n4js.xtext.resourceset.XtextResourceLocator.getResource(XtextResourceLocator.java:76)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$ResourceLocator.basicGetResource(ResourceSetImpl.java:743)
	at org.eclipse.n4js.ts.scoping.builtin.BuiltInSchemeResourceLocator.getResource(BuiltInSchemeResourceLocator.java:42)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$ResourceLocator.basicGetResource(ResourceSetImpl.java:743)
	at org.eclipse.n4js.ide.xtext.server.WorkspaceAwareResourceLocator.getResource(WorkspaceAwareResourceLocator.java:50)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:352)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:236)
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:25)
	at org.eclipse.n4js.ide.xtext.server.build.XClusteringStorageAwareResourceLoader.executeClustered(XClusteringStorageAwareResourceLoader.java:69)
	at org.eclipse.n4js.ide.xtext.server.build.XBuildContext.executeClustered(XBuildContext.java:61)
	at org.eclipse.n4js.ide.xtext.server.build.XIndexer.getDeltasForChangedResources(XIndexer.java:277)
	at org.eclipse.n4js.ide.xtext.server.build.XIndexer.computeAndIndexAffected(XIndexer.java:240)
	at org.eclipse.n4js.ide.xtext.server.build.XStatefulIncrementalBuilder.launch(XStatefulIncrementalBuilder.java:158)
	at org.eclipse.n4js.ide.xtext.server.build.XIncrementalBuilder.build(XIncrementalBuilder.java:61)
	at org.eclipse.n4js.ide.xtext.server.build.XIncrementalBuilder.build(XIncrementalBuilder.java:39)
	at org.eclipse.n4js.ide.xtext.server.XProjectManager.doBuild(XProjectManager.java:197)
	at org.eclipse.n4js.ide.xtext.server.XProjectManager.doIncrementalBuild(XProjectManager.java:181)
	at org.eclipse.n4js.ide.xtext.server.XBuildManager.doIncrementalBuild(XBuildManager.java:326)
	at org.eclipse.n4js.ide.xtext.server.XBuildManager.lambda$0(XBuildManager.java:286)
	at org.eclipse.n4js.ide.xtext.server.XWorkspaceManager.lambda$0(XWorkspaceManager.java:254)
	at org.eclipse.n4js.ide.xtext.server.LSPBuilder.lambda$5(LSPBuilder.java:183)
	at org.eclipse.n4js.ide.xtext.server.concurrent.LSPExecutorService$QueuedTask.run(LSPExecutorService.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.FileNotFoundException: /Users/mark-oliver.reiser/Desktop/temp-n4js-test/singleProject/ProjectA/src/A01.n4js (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.eclipse.emf.ecore.resource.impl.FileURIHandlerImpl.createInputStream(FileURIHandlerImpl.java:99)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
	at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:298)
	at org.eclipse.n4js.xtext.resourceset.EmptyAuthorityAddingNormalizer.createInputStream(EmptyAuthorityAddingNormalizer.java:99)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.load(StorageAwareResource.java:79)
	at org.eclipse.n4js.resource.N4JSResource.superLoad(N4JSResource.java:577)
	at org.eclipse.n4js.resource.N4JSResource.load(N4JSResource.java:859)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 28 more
```

**Comment by mor-n4** [comment]
There is a first version of a fix on branch `GH-1789`. But it's incomplete: when following the steps above for reproducing the bug (rename), other exceptions in other parts of the builder show up.
