### ISSUE TITLE
RegularExpression language inadvertently exposes semi-functional UI support that crashes the generator

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#192]
The RegularExpression Xtext language that is meant to be used inside N4JS code exposes its own UI support. That means that it is possible to create `.regex` files in a N4JS IDE that are validated correctly. Valid files however, won't be compiled correctly, as our current generator infrastructure cannot handle them correctly.

Valid `.regex` files lead to the following exceptions:

```
org.eclipse.n4js.generator.common.GeneratorException: Severe error occurred in transpiler=es message=Given resource is not an N4JSResource. org.eclipse.xtext.linking.lazy.LazyLinkingResource@55452c uri='platform:/resource/Test/test/test.regex'.
	at org.eclipse.n4js.generator.common.ExceptionHandler.handleError(ExceptionHandler.java:21)
	at org.eclipse.n4js.generator.common.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:173)
	at org.eclipse.n4js.generator.CompositeGenerator.lambda$0(CompositeGenerator.java:88)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
	at org.eclipse.n4js.generator.CompositeGenerator.useTranspilerType(CompositeGenerator.java:86)
	at org.eclipse.n4js.generator.CompositeGenerator.doGenerate(CompositeGenerator.java:62)
	at org.eclipse.n4js.ui.building.instructions.BuildInstruction.handleChangedContents(BuildInstruction.java:200)
	at org.eclipse.n4js.ui.building.instructions.BuildInstruction.process(BuildInstruction.java:128)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.updateMarkers(N4JSGenerateImmediatelyBuilderState.java:227)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:187)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at org.eclipse.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:77)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at org.eclipse.n4js.ui.building.N4JSBuildTypeTrackingBuilder.incrementalBuild(N4JSBuildTypeTrackingBuilder.java:54)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.IllegalArgumentException: Given resource is not an N4JSResource. org.eclipse.xtext.linking.lazy.LazyLinkingResource@55452c uri='platform:/resource/Test/test/test.regex'
	at org.eclipse.n4js.transpiler.es.EcmaScriptSubGenerator.internalDoGenerate(EcmaScriptSubGenerator.java:87)
	at org.eclipse.n4js.generator.common.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:122)
	... 39 more
```

This also results in a 'Severe error occurred while transpiling module..' marker on the `.regex` file.

Simply removing the UI support (editor etc.) will not fully fix this problem, since `.regex` will still be picked up by a clean-build (or headless build?) and cause the aforementioned issue with the generators.

**Comment by lbeurerkellner** [comment]
The same generator exception is thrown for `.n4ts` resources.
