### ISSUE TITLE
Exceptions when changing language mode of newly created, unsaved editor to "n4js" in VSCode

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1941]
To reproduce:

1. open VSCode with an N4JS workspace.
2. open an N4JS file to start N4JS LSP server.
3. open a new, unsaved editor with `CMD+N` and edit a bit
   --> works fine; no exceptions yet.
4. change the language mode of the new, unsaved file to "n4js", using `CMD+Shift+P` and "Change Language Mode"
   --> a first exception will be thrown.
5. edit a bit
   --> another exception will be thrown after each edit.

It is nice that after saving the new editor/file with a legal N4JS file name and extension everything is healed (no more exceptions; validations, etc. work fine in the editor without closing/reopening the file).

NOTE: new, unsaved editors have a URI of `untitled:Untitled-<n>`, with n = 1, 2, ...

First exception (when opening the new editor):
```
java.lang.IllegalStateException: unable to create resource for URI: untitled:Untitled-1
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskContext.initContext(ResourceTaskContext.java:265)
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskManager.lambda$0(ResourceTaskManager.java:124)
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskManager.lambda$3(ResourceTaskManager.java:177)
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskManager.lambda$5(ResourceTaskManager.java:247)
	at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
	at org.eclipse.n4js.ide.xtext.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
All following exceptions (when editing):
```
java.lang.IllegalStateException: trying to refresh a resource that was not yet initialized: untitled:Untitled-1
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskContext.prepareRefresh(ResourceTaskContext.java:310)
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskContext.refreshContext(ResourceTaskContext.java:327)
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskManager.lambda$1(ResourceTaskManager.java:138)
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskManager.lambda$3(ResourceTaskManager.java:177)
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskManager.lambda$5(ResourceTaskManager.java:247)
	at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
	at org.eclipse.n4js.ide.xtext.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mor-n4** [comment]
This is replaced by the more general story #1942.

Closing this as DUPLICATE.
