### ISSUE TITLE
IndexOutOfBoundsException in java.util.ArrayList used inside ContentAssistContextFactory

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#2000]
No way to reproduce this is known, so for now this ticket is only intended to collect information and as a basis for further investigation.

Stack trace:
```
ERROR - java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.doCreateContexts(ContentAssistContextFactory.java:180)
	at org.eclipse.n4js.ide.editor.contentassist.N4JSContentAssistContextFactory.doCreateContexts(N4JSContentAssistContextFactory.java:40)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.create(ContentAssistContextFactory.java:130)
	at org.eclipse.n4js.ide.xtext.server.contentassist.XContentAssistService.createProposals(XContentAssistService.java:94)
	at org.eclipse.n4js.ide.editor.contentassist.N4JSContentAssistService.createProposals(N4JSContentAssistService.java:35)
	at org.eclipse.n4js.ide.xtext.server.contentassist.XContentAssistService.createCompletionList(XContentAssistService.java:69)
	at org.eclipse.n4js.ide.xtext.server.TextDocumentFrontend.completion(TextDocumentFrontend.java:194)
	at org.eclipse.n4js.ide.xtext.server.TextDocumentFrontend.lambda$0(TextDocumentFrontend.java:177)
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskManager.lambda$5(ResourceTaskManager.java:247)
	at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
	at org.eclipse.n4js.ide.xtext.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.setParamConfigAndUpdateOffset(FollowElementComputer.java:174)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:99)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:85)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:75)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:80)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.doCreateContexts(ContentAssistContextFactory.java:318)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.PartialContentAssistContextFactory.handleLastCompleteNodeIsAtEndOfDatatypeNode(PartialContentAssistContextFactory.java:64)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory$2.call(ContentAssistContextFactory.java:160)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory$2.call(ContentAssistContextFactory.java:157)
	... 4 more
```

**Comment by mor-n4** [comment]
Probably a different problem, but also in the `ContentAssistContextFactory`:
```
ERROR - org.eclipse.xtext.ide.editor.contentassist.antlr.internal.InfiniteRecursion
java.util.concurrent.ExecutionException: org.eclipse.xtext.ide.editor.contentassist.antlr.internal.InfiniteRecursion
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.doCreateContexts(ContentAssistContextFactory.java:180)
	at org.eclipse.n4js.ide.editor.contentassist.N4JSContentAssistContextFactory.doCreateContexts(N4JSContentAssistContextFactory.java:40)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.create(ContentAssistContextFactory.java:130)
	at org.eclipse.n4js.ide.xtext.server.contentassist.XContentAssistService.createProposals(XContentAssistService.java:94)
	at org.eclipse.n4js.ide.editor.contentassist.N4JSContentAssistService.createProposals(N4JSContentAssistService.java:35)
	at org.eclipse.n4js.ide.xtext.server.contentassist.XContentAssistService.createCompletionList(XContentAssistService.java:69)
	at org.eclipse.n4js.ide.xtext.server.TextDocumentFrontend.completion(TextDocumentFrontend.java:194)
	at org.eclipse.n4js.ide.xtext.server.TextDocumentFrontend.lambda$0(TextDocumentFrontend.java:177)
	at org.eclipse.n4js.ide.xtext.server.ResourceTaskManager.lambda$5(ResourceTaskManager.java:247)
	at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
	at org.eclipse.n4js.ide.xtext.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.eclipse.xtext.ide.editor.contentassist.antlr.internal.InfiniteRecursion
	at org.eclipse.xtext.ide.editor.contentassist.antlr.internal.BaseInternalContentAssistParser.infiniteRecursion(BaseInternalContentAssistParser.java:132)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.internal.BaseInternalContentAssistParser.before(BaseInternalContentAssistParser.java:122)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group_3_0__4__Impl(InternalN4JSParser.java:63883)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group_3_0__4(InternalN4JSParser.java:63875)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group_3_0__3(InternalN4JSParser.java:63861)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group_3_0__2(InternalN4JSParser.java:63845)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group_3_0__1(InternalN4JSParser.java:63805)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group_3_0__0(InternalN4JSParser.java:63789)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Alternatives_3(InternalN4JSParser.java:18622)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group__3__Impl(InternalN4JSParser.java:63779)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group__3(InternalN4JSParser.java:63770)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group__2(InternalN4JSParser.java:63738)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group__1(InternalN4JSParser.java:63719)
	at org.eclipse.n4js.ide.contentassist.antlr.internal.InternalN4JSParser.rule__JSXElement__Group__0(InternalN4JSParser.java:63703)
	at jdk.internal.reflect.GeneratedMethodAccessor204.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.BaseContentAssistParser.getFollowElements(BaseContentAssistParser.java:171)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.BaseContentAssistParser.getFollowElements(BaseContentAssistParser.java:241)
	at org.eclipse.n4js.ide.editor.contentassist.CustomN4JSParser.doGetFollowElements(CustomN4JSParser.java:476)
	at org.eclipse.n4js.ide.editor.contentassist.CustomN4JSParser.resetAndGetFollowElements(CustomN4JSParser.java:434)
	at org.eclipse.n4js.ide.editor.contentassist.CustomN4JSParser.adjustASIAndCollectFollowElements(CustomN4JSParser.java:365)
	at org.eclipse.n4js.ide.editor.contentassist.CustomN4JSParser.getFollowElements(CustomN4JSParser.java:229)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.PartialContentAssistContextFactory.parseFollowElements(PartialContentAssistContextFactory.java:45)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.PartialContentAssistContextFactory.handleLastCompleteNodeAsPartOfDatatypeNode(PartialContentAssistContextFactory.java:51)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory$1.call(ContentAssistContextFactory.java:148)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory$1.call(ContentAssistContextFactory.java:145)
	... 4 more
```

**Comment by mor-n4** [comment]
Another example:
```
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.doCreateContexts(ContentAssistContextFactory.java:180)
	at org.eclipse.n4js.ide.editor.contentassist.N4JSContentAssistContextFactory.doCreateContexts(N4JSContentAssistContextFactory.java:40)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.create(ContentAssistContextFactory.java:130)
	at org.eclipse.n4js.xtext.ide.server.contentassist.XContentAssistService.createProposals(XContentAssistService.java:94)
	at org.eclipse.n4js.ide.editor.contentassist.N4JSContentAssistService.createProposals(N4JSContentAssistService.java:35)
	at org.eclipse.n4js.xtext.ide.server.contentassist.XContentAssistService.createCompletionList(XContentAssistService.java:69)
	at org.eclipse.n4js.xtext.ide.server.TextDocumentFrontend.completion(TextDocumentFrontend.java:194)
	at org.eclipse.n4js.ide.server.N4JSTextDocumentFrontend.completion(N4JSTextDocumentFrontend.java:82)
	at org.eclipse.n4js.xtext.ide.server.TextDocumentFrontend.lambda$0(TextDocumentFrontend.java:177)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskManager.lambda$5(ResourceTaskManager.java:263)
	at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
	at org.eclipse.n4js.xtext.ide.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.setParamConfigAndUpdateOffset(FollowElementComputer.java:174)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:99)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:85)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:75)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer.computeFollowElements(FollowElementComputer.java:80)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.doCreateContexts(ContentAssistContextFactory.java:318)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.PartialContentAssistContextFactory.handleLastCompleteNodeAsPartOfDatatypeNode(PartialContentAssistContextFactory.java:53)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory$1.call(ContentAssistContextFactory.java:148)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory$1.call(ContentAssistContextFactory.java:145)
	... 4 more
```
