### ISSUE TITLE
Compiler should exit with return code != 0 in case of exceptions

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#2053]
Note that in the example below, the builder recognises a problem (`... initial build ABORTED due to exception:`) but still exits with exit code 0.

```

$ n4jsc compile . --clean
info goal=compile; dir=.; options=--clean; vmOptions= 
Connected to N4JS LSP server (0.24.27.v20210127-1152)
Clean results - Deleted: 0, Duration: 19.26 ms
Initial build ...
0    ERROR N4JSResource       - exception during proxy resolution in super class of N4JSResource:
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.resize(Unknown Source)
	at java.base/java.util.HashMap.putVal(Unknown Source)
	at java.base/java.util.HashMap.put(Unknown Source)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.doGetUriToDescription(ResourceDescriptionsBasedContainer.java:113)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.getUriToDescription(ResourceDescriptionsBasedContainer.java:103)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.getResourceDescriptionCount(ResourceDescriptionsBasedContainer.java:81)
	at org.eclipse.xtext.resource.containers.FilterUriContainer.isEmpty(FilterUriContainer.java:39)
	at org.eclipse.n4js.scoping.utils.UserDataAwareScope.createScope(UserDataAwareScope.java:100)
	at org.eclipse.n4js.scoping.N4JSGlobalScopeProvider.createContainerScopeWithContext(N4JSGlobalScopeProvider.java:102)
	at org.eclipse.xtext.scoping.impl.DefaultGlobalScopeProvider.getScope(DefaultGlobalScopeProvider.java:54)
	at org.eclipse.n4js.scoping.N4JSGlobalScopeProvider.getScope(N4JSGlobalScopeProvider.java:61)
	at org.eclipse.n4js.ts.scoping.builtin.DefaultN4GlobalScopeProvider.getScope(DefaultN4GlobalScopeProvider.java:42)
	at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeProvider.getScope(AbstractGlobalScopeProvider.java:50)
	at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeDelegatingScopeProvider.getGlobalScope(AbstractGlobalScopeDelegatingScopeProvider.java:46)
	at org.eclipse.n4js.scoping.imports.N4JSImportedNamespaceAwareLocalScopeProvider.getResourceScope(N4JSImportedNamespaceAwareLocalScopeProvider.java:69)
	at org.eclipse.xtext.scoping.impl.ImportedNamespaceAwareLocalScopeProvider.getScope(ImportedNamespaceAwareLocalScopeProvider.java:97)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScriptBaseScope(N4JSScopeProvider.java:591)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.buildLexicalEnvironmentScope(N4JSScopeProvider.java:580)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.lambda$2(N4JSScopeProvider.java:561)
	at org.eclipse.n4js.scoping.N4JSScopeProvider$$Lambda$182/0x000000010051ec40.get(Unknown Source)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getLexicalEnvironmentScope(N4JSScopeProvider.java:563)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.scope_IdentifierRef_id(N4JSScopeProvider.java:530)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScopeForContext(N4JSScopeProvider.java:339)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getN4JSScope(N4JSScopeProvider.java:286)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScope(N4JSScopeProvider.java:256)
	at org.eclipse.n4js.resource.ErrorAwareLinkingService.getScope(ErrorAwareLinkingService.java:76)
	at org.eclipse.n4js.resource.ErrorAwareLinkingService.getLinkedObjects(ErrorAwareLinkingService.java:90)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:265)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:236)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:119)
	at org.eclipse.n4js.resource.N4JSResource.getEObject(N4JSResource.java:1182)
3    ERROR UtilN4             - exception while post-processing resource file:///builds/numberfour/js/onlinepresence-qa/node_modules/eu.numberfour.stdlib.model.gen/src/n4js-gen/n4/metacompany/documents/DocumentTemplateUtility.n4js
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.resize(Unknown Source)
	at java.base/java.util.HashMap.putVal(Unknown Source)
	at java.base/java.util.HashMap.put(Unknown Source)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.doGetUriToDescription(ResourceDescriptionsBasedContainer.java:113)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.getUriToDescription(ResourceDescriptionsBasedContainer.java:103)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.getResourceDescriptionCount(ResourceDescriptionsBasedContainer.java:81)
	at org.eclipse.xtext.resource.containers.FilterUriContainer.isEmpty(FilterUriContainer.java:39)
	at org.eclipse.n4js.scoping.utils.UserDataAwareScope.createScope(UserDataAwareScope.java:100)
	at org.eclipse.n4js.scoping.N4JSGlobalScopeProvider.createContainerScopeWithContext(N4JSGlobalScopeProvider.java:102)
	at org.eclipse.xtext.scoping.impl.DefaultGlobalScopeProvider.getScope(DefaultGlobalScopeProvider.java:54)
	at org.eclipse.n4js.scoping.N4JSGlobalScopeProvider.getScope(N4JSGlobalScopeProvider.java:61)
	at org.eclipse.n4js.ts.scoping.builtin.DefaultN4GlobalScopeProvider.getScope(DefaultN4GlobalScopeProvider.java:42)
	at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeProvider.getScope(AbstractGlobalScopeProvider.java:50)
	at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeDelegatingScopeProvider.getGlobalScope(AbstractGlobalScopeDelegatingScopeProvider.java:46)
	at org.eclipse.n4js.scoping.imports.N4JSImportedNamespaceAwareLocalScopeProvider.getResourceScope(N4JSImportedNamespaceAwareLocalScopeProvider.java:69)
	at org.eclipse.xtext.scoping.impl.ImportedNamespaceAwareLocalScopeProvider.getScope(ImportedNamespaceAwareLocalScopeProvider.java:97)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScriptBaseScope(N4JSScopeProvider.java:591)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.buildLexicalEnvironmentScope(N4JSScopeProvider.java:580)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.lambda$2(N4JSScopeProvider.java:561)
	at org.eclipse.n4js.scoping.N4JSScopeProvider$$Lambda$182/0x000000010051ec40.get(Unknown Source)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getLexicalEnvironmentScope(N4JSScopeProvider.java:563)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.scope_IdentifierRef_id(N4JSScopeProvider.java:530)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScopeForContext(N4JSScopeProvider.java:339)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getN4JSScope(N4JSScopeProvider.java:286)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScope(N4JSScopeProvider.java:256)
	at org.eclipse.n4js.resource.ErrorAwareLinkingService.getScope(ErrorAwareLinkingService.java:76)
	at org.eclipse.n4js.resource.ErrorAwareLinkingService.getLinkedObjects(ErrorAwareLinkingService.java:90)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:265)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:236)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:119)
	at org.eclipse.n4js.resource.N4JSResource.getEObject(N4JSResource.java:1182)
... initial build ABORTED due to exception:
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.resize(Unknown Source)
	at java.base/java.util.HashMap.putVal(Unknown Source)
	at java.base/java.util.HashMap.put(Unknown Source)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.doGetUriToDescription(ResourceDescriptionsBasedContainer.java:113)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.getUriToDescription(ResourceDescriptionsBasedContainer.java:103)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.getResourceDescriptionCount(ResourceDescriptionsBasedContainer.java:81)
	at org.eclipse.xtext.resource.containers.FilterUriContainer.isEmpty(FilterUriContainer.java:39)
	at org.eclipse.n4js.scoping.utils.UserDataAwareScope.createScope(UserDataAwareScope.java:100)
	at org.eclipse.n4js.scoping.N4JSGlobalScopeProvider.createContainerScopeWithContext(N4JSGlobalScopeProvider.java:102)
	at org.eclipse.xtext.scoping.impl.DefaultGlobalScopeProvider.getScope(DefaultGlobalScopeProvider.java:54)
	at org.eclipse.n4js.scoping.N4JSGlobalScopeProvider.getScope(N4JSGlobalScopeProvider.java:61)
	at org.eclipse.n4js.ts.scoping.builtin.DefaultN4GlobalScopeProvider.getScope(DefaultN4GlobalScopeProvider.java:42)
	at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeProvider.getScope(AbstractGlobalScopeProvider.java:50)
	at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeDelegatingScopeProvider.getGlobalScope(AbstractGlobalScopeDelegatingScopeProvider.java:46)
	at org.eclipse.n4js.scoping.imports.N4JSImportedNamespaceAwareLocalScopeProvider.getResourceScope(N4JSImportedNamespaceAwareLocalScopeProvider.java:69)
	at org.eclipse.xtext.scoping.impl.ImportedNamespaceAwareLocalScopeProvider.getScope(ImportedNamespaceAwareLocalScopeProvider.java:97)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScriptBaseScope(N4JSScopeProvider.java:591)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.buildLexicalEnvironmentScope(N4JSScopeProvider.java:580)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.lambda$2(N4JSScopeProvider.java:561)
	at org.eclipse.n4js.scoping.N4JSScopeProvider$$Lambda$182/0x000000010051ec40.get(Unknown Source)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getLexicalEnvironmentScope(N4JSScopeProvider.java:563)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.scope_IdentifierRef_id(N4JSScopeProvider.java:530)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScopeForContext(N4JSScopeProvider.java:339)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getN4JSScope(N4JSScopeProvider.java:286)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScope(N4JSScopeProvider.java:256)
	at org.eclipse.n4js.resource.ErrorAwareLinkingService.getScope(ErrorAwareLinkingService.java:76)
	at org.eclipse.n4js.resource.ErrorAwareLinkingService.getLinkedObjects(ErrorAwareLinkingService.java:90)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:265)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:236)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:119)
	at org.eclipse.n4js.resource.N4JSResource.getEObject(N4JSResource.java:1182)
3962 ERROR QueuedExecutorService$QueuedTask - error during queued task: 
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.resize(Unknown Source)
	at java.base/java.util.HashMap.putVal(Unknown Source)
	at java.base/java.util.HashMap.put(Unknown Source)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.doGetUriToDescription(ResourceDescriptionsBasedContainer.java:113)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.getUriToDescription(ResourceDescriptionsBasedContainer.java:103)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsBasedContainer.getResourceDescriptionCount(ResourceDescriptionsBasedContainer.java:81)
	at org.eclipse.xtext.resource.containers.FilterUriContainer.isEmpty(FilterUriContainer.java:39)
	at org.eclipse.n4js.scoping.utils.UserDataAwareScope.createScope(UserDataAwareScope.java:100)
	at org.eclipse.n4js.scoping.N4JSGlobalScopeProvider.createContainerScopeWithContext(N4JSGlobalScopeProvider.java:102)
	at org.eclipse.xtext.scoping.impl.DefaultGlobalScopeProvider.getScope(DefaultGlobalScopeProvider.java:54)
	at org.eclipse.n4js.scoping.N4JSGlobalScopeProvider.getScope(N4JSGlobalScopeProvider.java:61)
	at org.eclipse.n4js.ts.scoping.builtin.DefaultN4GlobalScopeProvider.getScope(DefaultN4GlobalScopeProvider.java:42)
	at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeProvider.getScope(AbstractGlobalScopeProvider.java:50)
	at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeDelegatingScopeProvider.getGlobalScope(AbstractGlobalScopeDelegatingScopeProvider.java:46)
	at org.eclipse.n4js.scoping.imports.N4JSImportedNamespaceAwareLocalScopeProvider.getResourceScope(N4JSImportedNamespaceAwareLocalScopeProvider.java:69)
	at org.eclipse.xtext.scoping.impl.ImportedNamespaceAwareLocalScopeProvider.getScope(ImportedNamespaceAwareLocalScopeProvider.java:97)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScriptBaseScope(N4JSScopeProvider.java:591)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.buildLexicalEnvironmentScope(N4JSScopeProvider.java:580)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.lambda$2(N4JSScopeProvider.java:561)
	at org.eclipse.n4js.scoping.N4JSScopeProvider$$Lambda$182/0x000000010051ec40.get(Unknown Source)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getLexicalEnvironmentScope(N4JSScopeProvider.java:563)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.scope_IdentifierRef_id(N4JSScopeProvider.java:530)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScopeForContext(N4JSScopeProvider.java:339)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getN4JSScope(N4JSScopeProvider.java:286)
	at org.eclipse.n4js.scoping.N4JSScopeProvider.getScope(N4JSScopeProvider.java:256)
	at org.eclipse.n4js.resource.ErrorAwareLinkingService.getScope(ErrorAwareLinkingService.java:76)
	at org.eclipse.n4js.resource.ErrorAwareLinkingService.getLinkedObjects(ErrorAwareLinkingService.java:90)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:265)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:236)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:119)
	at org.eclipse.n4js.resource.N4JSResource.getEObject(N4JSResource.java:1182)
Compile results - Transpiled: 0, Deleted: 0, Errors: 0, Warnings: 0, Duration: 5.834 min
Done in 353.93s.
```

**Comment by mmews-n4** [comment]
@mor-n4 Since I just noticed: Do we have a ticket to clean-up the outputs of the compiler? Some outputs like `Initial build ...` and `Done in 353.93s` are only useful for the LSP case.
