### ISSUE TITLE
Xt test framework confused by some valid input

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#2089]
Some input causes the Xt tests to get confused:
1. If an `.xt` file contains input such as
   ```
   {
   	"name": "SomeProject",
   	"version": "0.0.1",
   	"n4js": {
   		"projectType": "library",
   		"output": "src-gen",
   		"sources": {
   			"source": [
   				"src/p/q/*.js"
   			]
   		},
   		"moduleFilters": {
   			"noValidate": [
   				"p/q/*",
   				// XPECT errors --> "some expected error" at ""***/A""
   				"***/A",
   				{
   					"sourceContainer": "src2",
   					"module": "**/*"
   				}
   			]
   		}
   	}
   }
   ```
   it reports incorrect errors and overlooks valid errors, because the sequence `/*` is interpreted as the beginning and `*/` as the end of a multi-line comment.
2. Files without file extensions in the `Workspace` section of the Xt setup preamble cause exceptions:
   ```
   java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 5
   	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
   	at java.base/java.lang.String.substring(String.java:1874)
   	at org.eclipse.n4js.ide.tests.helper.server.xt.XtSetupParser.parseFile(XtSetupParser.java:331)
   	at org.eclipse.n4js.ide.tests.helper.server.xt.XtSetupParser.parseContainerRest(XtSetupParser.java:247)
   	at org.eclipse.n4js.ide.tests.helper.server.xt.XtSetupParser.parseFolder(XtSetupParser.java:271)
   	at org.eclipse.n4js.ide.tests.helper.server.xt.XtSetupParser.parseContainerRest(XtSetupParser.java:242)
   	at org.eclipse.n4js.ide.tests.helper.server.xt.XtSetupParser.parseProject(XtSetupParser.java:225)
   [...]
   ```
3. In addition, there are problems caused by the fact that the `@BeforeClass`, `@Before`, `@After`, `@AfterClass` methods in `AbstractIdeTest` are not executed when running IDE tests through the Xt framework.

**Comment by mor-n4** [comment]
FYI: while not related to the title of this ticket, I also fixed on this branch the problem that system output redirection of IDE tests did not work correctly in Xt tests.
