### ISSUE TITLE
Exceptions when creating/deleting a workspace project that shadows a node_modules project

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#2121]
Given a yarn workspace, when creating a project in the "packages" folder that shadows an existing project in the `node_modules` folder, then the following exception is thrown:
```
java.lang.NullPointerException
  at org.eclipse.n4js.xtext.workspace.BuildOrderIterator.visit(BuildOrderIterator.java:53)
  at org.eclipse.n4js.xtext.workspace.BuildOrderFactory.createBuildOrderIterator(BuildOrderFactory.java:37)
  at org.eclipse.n4js.xtext.ide.server.build.XWorkspaceBuilder.doIncrementalBuild(XWorkspaceBuilder.java:429)
  at org.eclipse.n4js.xtext.ide.server.build.XWorkspaceBuilder.doIncrementalWorkspaceUpdateAndBuild(XWorkspaceBuilder.java:369)
  at org.eclipse.n4js.xtext.ide.server.build.BuilderFrontend.lambda$6(BuilderFrontend.java:192)
  at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
  at org.eclipse.n4js.xtext.ide.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:834)
```
The same happens when such a shadowing project is deleted from the "packages" folder.

NOTE: shadowing in principle works fine. This bug is about the incremental build triggered when entering/leaving the shadowing state by creating/deleting a shadowing project.

**Comment by mor-n4** [comment]
In this context I also witnessed the following stack trace, but could not find a way to reproduce it:
```
java.lang.IllegalStateException: Dependency-inverse visit order not supported: from @n4jsd/debug to onlinepresence
  at org.eclipse.n4js.xtext.workspace.BuildOrderIterator.visit(BuildOrderIterator.java:58)
  at org.eclipse.n4js.xtext.workspace.BuildOrderIterator.visitAffected(BuildOrderIterator.java:77)
  at org.eclipse.n4js.xtext.ide.server.build.XWorkspaceBuilder.doIncrementalBuild(XWorkspaceBuilder.java:463)
  at org.eclipse.n4js.xtext.ide.server.build.XWorkspaceBuilder.doIncrementalWorkspaceUpdateAndBuild(XWorkspaceBuilder.java:369)
  at org.eclipse.n4js.xtext.ide.server.build.BuilderFrontend.lambda$6(BuilderFrontend.java:192)
  at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
  at org.eclipse.n4js.xtext.ide.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```
