### ISSUE TITLE
Cannot install derived state in resource without AST IllegalStateException

### ISSUE THREAD

**Issue by qtran-n4** [eclipse/n4js#213]
Some times, we get the following exception in the console. It is not easy to reproduce:

```
!ENTRY org.apache.log4j 4 0 2017-09-05 18:52:20.483
!MESSAGE org.eclipse.xtext.linking.lazy.LazyLinkingResource  - resolution of uriFragment '|6' failed.

!STACK 0
java.lang.IllegalStateException: cannot install derived state in resource without AST
	at org.eclipse.n4js.resource.N4JSDerivedStateComputer.installDerivedState(N4JSDerivedStateComputer.java:47)
	at org.eclipse.n4js.resource.N4JSResource.installDerivedState(N4JSResource.java:773)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.getContents(DerivedStateAwareResource.java:97)
	at org.eclipse.n4js.resource.N4JSResource.getContents(N4JSResource.java:269)
	at org.eclipse.n4js.resource.N4JSResource.getModule(N4JSResource.java:1138)
	at org.eclipse.n4js.resource.N4JSResource.isLoadedFromDescription(N4JSResource.java:380)
	at org.eclipse.n4js.scoping.utils.CanLoadFromDescriptionHelper.mustLoadFromSource(CanLoadFromDescriptionHelper.java:99)
	at org.eclipse.n4js.ui.editor.EditorAwareCanLoadFromDescriptionHelper.mustLoadFromSource(EditorAwareCanLoadFromDescriptionHelper.java:53)
	at org.eclipse.n4js.scoping.utils.UserDataAwareScope.resolve(UserDataAwareScope.java:165)
	at org.eclipse.n4js.scoping.utils.UserDataAwareScope.access$0(UserDataAwareScope.java:156)
	at org.eclipse.n4js.scoping.utils.UserDataAwareScope$1.apply(UserDataAwareScope.java:220)
	at org.eclipse.n4js.scoping.utils.UserDataAwareScope$1.apply(UserDataAwareScope.java:1)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators.size(Iterators.java:187)
	at com.google.common.collect.Iterables.size(Iterables.java:108)
	at org.eclipse.n4js.scoping.utils.ProjectImportEnablingScope.getSingleElement(ProjectImportEnablingScope.java:127)
	at org.eclipse.n4js.xtext.scoping.FilterWithErrorMarkerScope.getSingleElement(FilterWithErrorMarkerScope.java:93)
	at org.eclipse.n4js.resource.ErrorAwareLinkingService.getLinkedObjects(ErrorAwareLinkingService.java:88)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:247)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:222)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:120)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:203)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:243)
	at org.eclipse.n4js.resource.N4JSResource.doResolveProxy(N4JSResource.java:892)
	at org.eclipse.n4js.utils.emf.ProxyResolvingEObjectImpl.eResolveProxy(ProxyResolvingEObjectImpl.java:32)
	at org.eclipse.n4js.n4JS.impl.ImportDeclarationImpl.getModule(ImportDeclarationImpl.java:150)
```

**Comment by mor-n4** [comment]
The case shown in the above stack trace was fixed as part of #228 with the change in method `N4JSResource#getModule()`: this method no longer calls `#getContents()` as in the above stack trace.

Closing this issue now.
