### ISSUE TITLE
NullPointerException when hovering

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#2170]
For example:
```
ERROR - error during queued task: 
java.lang.NullPointerException
	at org.eclipse.n4js.ide.server.hover.N4JSHoverService.hover(N4JSHoverService.java:60)
	at org.eclipse.xtext.ide.server.hover.HoverService.hover(HoverService.java:55)
	at org.eclipse.n4js.xtext.ide.server.TextDocumentFrontend.hover(TextDocumentFrontend.java:293)
	at org.eclipse.n4js.xtext.ide.server.TextDocumentFrontend.lambda$5(TextDocumentFrontend.java:279)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskManager.lambda$5(ResourceTaskManager.java:332)
	at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
	at org.eclipse.n4js.xtext.ide.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERROR - Server errors: 730 / textDocument/hover
[Error - 9:51:00 AM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.n4js.xtext.ide.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:137)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at org.eclipse.n4js.ide.server.hover.N4JSHoverService.hover(N4JSHoverService.java:60)
	at org.eclipse.xtext.ide.server.hover.HoverService.hover(HoverService.java:55)
	at org.eclipse.n4js.xtext.ide.server.TextDocumentFrontend.hover(TextDocumentFrontend.java:293)
	at org.eclipse.n4js.xtext.ide.server.TextDocumentFrontend.lambda$5(TextDocumentFrontend.java:279)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskManager.lambda$5(ResourceTaskManager.java:332)
	at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
	at org.eclipse.n4js.xtext.ide.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
	... 5 more
Building ...
... build done.
ERROR - error during queued task: 
java.lang.NullPointerException
	at org.eclipse.n4js.ide.server.hover.N4JSHoverService.hover(N4JSHoverService.java:60)
	at org.eclipse.xtext.ide.server.hover.HoverService.hover(HoverService.java:55)
	at org.eclipse.n4js.xtext.ide.server.TextDocumentFrontend.hover(TextDocumentFrontend.java:293)
	at org.eclipse.n4js.xtext.ide.server.TextDocumentFrontend.lambda$5(TextDocumentFrontend.java:279)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskManager.lambda$5(ResourceTaskManager.java:332)
	at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
	at org.eclipse.n4js.xtext.ide.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERROR - Server errors: 757 / textDocument/hover
[Error - 9:51:20 AM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.n4js.xtext.ide.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:137)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at org.eclipse.n4js.ide.server.hover.N4JSHoverService.hover(N4JSHoverService.java:60)
	at org.eclipse.xtext.ide.server.hover.HoverService.hover(HoverService.java:55)
	at org.eclipse.n4js.xtext.ide.server.TextDocumentFrontend.hover(TextDocumentFrontend.java:293)
	at org.eclipse.n4js.xtext.ide.server.TextDocumentFrontend.lambda$5(TextDocumentFrontend.java:279)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskManager.lambda$5(ResourceTaskManager.java:332)
	at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
	at org.eclipse.n4js.xtext.ide.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
	... 5 more
```

**Comment by mmews-n4** [comment]
done in #2171
