### ISSUE TITLE
Code with syntax error leads to exception

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#2186]
This snippet
```
class G<T> {}
new G<
```
will produce this exception:
```
java.lang.IllegalArgumentException: The 'no null' constraint is violated
	at org.eclipse.emf.common.util.AbstractEList.validate(AbstractEList.java:99)
	at org.eclipse.emf.ecore.util.EcoreEList.validate(EcoreEList.java:63)
	at org.eclipse.emf.common.util.BasicEList.addUnique(BasicEList.java:417)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.doAddUnique(NotifyingListImpl.java:325)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.addUnique(NotifyingListImpl.java:309)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:304)
	at org.eclipse.n4js.ts.utils.TypeUtils.createTypeRef(TypeUtils.java:217)
	at org.eclipse.n4js.ts.utils.TypeUtils.createTypeRef(TypeUtils.java:191)
	at org.eclipse.n4js.ts.utils.TypeUtils.createTypeRef(TypeUtils.java:180)
	at org.eclipse.n4js.ts.utils.TypeExtensions.ref(TypeExtensions.java:30)
	at org.eclipse.n4js.typesystem.utils.TypeSystemHelper.createTypeRefFromStaticType(TypeSystemHelper.java:559)
	at org.eclipse.n4js.typesystem.utils.TypeSystemHelper.createTypeRefFromStaticType(TypeSystemHelper.java:544)
	at org.eclipse.n4js.typesystem.TypeJudgment$TypeJudgmentSwitchForASTNodes.caseNewExpression(TypeJudgment.java:1147)
	at org.eclipse.n4js.typesystem.TypeJudgment$TypeJudgmentSwitchForASTNodes.caseNewExpression(TypeJudgment.java:1)
	at org.eclipse.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:1035)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.n4js.typesystem.TypeJudgment.doApply(TypeJudgment.java:224)
	at org.eclipse.n4js.typesystem.TypeJudgment.apply(TypeJudgment.java:208)
	at org.eclipse.n4js.typesystem.N4JSTypeSystem.use_type_judgment_from_PostProcessors(N4JSTypeSystem.java:105)
	at org.eclipse.n4js.postprocessing.AbstractProcessor.invokeTypeJudgmentToInferType(AbstractProcessor.java:99)
	at org.eclipse.n4js.postprocessing.TypeProcessor.typeNode2(TypeProcessor.java:148)
	at org.eclipse.n4js.postprocessing.TypeProcessor.typeNode(TypeProcessor.java:93)
	at org.eclipse.n4js.postprocessing.ASTProcessor.processNode_postChildren(ASTProcessor.java:389)
	at org.eclipse.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:249)
	at org.eclipse.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:245)
	at org.eclipse.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:245)
	at org.eclipse.n4js.postprocessing.ASTProcessor.processAST(ASTProcessor.java:182)
	at org.eclipse.n4js.postprocessing.ASTProcessor.processAST(ASTProcessor.java:144)
	at org.eclipse.n4js.postprocessing.N4JSPostProcessor.postProcessN4JSResource(N4JSPostProcessor.java:130)
	at org.eclipse.n4js.postprocessing.N4JSPostProcessor.performPostProcessing(N4JSPostProcessor.java:82)
	at org.eclipse.n4js.resource.PostProcessingAwareResource.doMainPostProcessing(PostProcessingAwareResource.java:323)
	at org.eclipse.n4js.resource.PostProcessingAwareResource.performPostProcessing(PostProcessingAwareResource.java:274)
	at org.eclipse.n4js.resource.N4JSResource.performPostProcessing(N4JSResource.java:1472)
	at org.eclipse.n4js.resource.PostProcessingAwareResource.resolveLazyCrossReferences(PostProcessingAwareResource.java:189)
	at org.eclipse.n4js.resource.N4JSResource.resolveLazyCrossReferences(N4JSResource.java:1482)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:505)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskContext.resolveResource(ResourceTaskContext.java:336)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskContext.resolveAndValidateResource(ResourceTaskContext.java:329)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskContext.refreshContext(ResourceTaskContext.java:321)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskManager.lambda$1(ResourceTaskManager.java:204)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskManager.lambda$3(ResourceTaskManager.java:254)
	at org.eclipse.n4js.xtext.ide.server.ResourceTaskManager.lambda$5(ResourceTaskManager.java:332)
	at org.eclipse.n4js.ide.server.concurrent.N4JSQueuedExecutorService.lambda$0(N4JSQueuedExecutorService.java:35)
	at org.eclipse.n4js.xtext.ide.server.QueuedExecutorService$QueuedTask.run(QueuedExecutorService.java:124)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mor-n4** [comment]
Probably this code is causing the problem:
https://github.com/eclipse/n4js/blob/bb5401826750ae4d3c6460aa0ad5697e22c989ae/plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/TypeSystemHelper.xtend#L447-L449

In case of syntax errors, `.typeArgs.map[typeRef]` might produce `null`-elements, so this should fix it:
```javascript
		return createTypeRefFromStaticType(G, ctr, paramAccess.typeArgs.map[typeRef].filterNull);
```

However, then the snippet from the issue description will still behave strangely, because issue markers are not updated as long as the syntax error is in the code. So probably there is some other, hidden exception being thrown. Needs to be investigated.
