### ISSUE TITLE
Empty value for optional JSX property causing exception in transpiler

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#2268]
Exception:
```
Severe error occurred in transpiler=es message=element to process may not be null.
java.lang.IllegalArgumentException: element to process may not be null
	at org.eclipse.n4js.transpiler.print.PrettyPrinterEcmaScript.process(PrettyPrinterEcmaScript.java:1257)
	at org.eclipse.n4js.transpiler.print.PrettyPrinterEcmaScript.caseParenExpression(PrettyPrinterEcmaScript.java:691)
	at org.eclipse.n4js.transpiler.print.PrettyPrinterEcmaScript.caseParenExpression(PrettyPrinterEcmaScript.java:1)
	at org.eclipse.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:745)
	at org.eclipse.n4js.transpiler.print.PrettyPrinterEcmaScript.doSwitch(PrettyPrinterEcmaScript.java:82)
	at org.eclipse.n4js.transpiler.print.PrettyPrinterEcmaScript.doSwitch(PrettyPrinterEcmaScript.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.n4js.transpiler.print.PrettyPrinterEcmaScript.doSwitch(PrettyPrinterEcmaScript.java:75)
	at org.eclipse.n4js.transpiler.print.PrettyPrinterEcmaScript.doSwitch(PrettyPrinterEcmaScript.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
```
To reproduce:
```javascript
import * as React from "react";

export public interface ~MyProps {
    public header?: React.ReactElement<?>;
}

export public function MyElement(props: MyProps): React.ReactElement<?> {
	return null;
}


let elem = <MyElement header={(
)}>

</MyElement>;
```
Note: if the line break after `let elem = <MyElement header={(` is removed, a syntax error is shown.

**Comment by mor-n4** [comment]
This seems to be a bug in the parser: it seems to accept empty parenthesis expression if they contain a line break.

The above exception can be reproduced with the following code:
```javascript
let x = (
);
```
When removing the line break, the parser correctly emits a syntax error:
```javascript
let x = (); // error: no viable alternative at input ')'
```
(BTW: if this is true, it makes sense that the transpiler throws an exception.)
