### ISSUE TITLE
n4jsc compilation failure if function name & variable name are same.

### ISSUE THREAD

**Issue by chanakyabhardwajj** [eclipse/n4js#247]
The following n4js code fails to compile
```
export public function options(items: Array<out ~r~LineItem> | ~r~Order, main: ~r~LineItem): Array<~r~LineItem> {
    const options: [~r~LineItem] = [];
    for (const item of iterable(items)) {
        if (!!item.dependsOn && item.dependsOn === main.id && item.resource
            && item.resource.classType === ResourceClassType.OPTION) {
            options.push(item);
        }
    }
    return options;
}
```

The n4jsc fails with the following error :
```
> Failed to build on /tmp/5a617972-d731-422b-9af0-11e567867fbe
13:22:32 { Error: ./src-gen/es/eu.numberfour.online-presence/n4/app/shared/model/core/LineItems.js
13:22:32 Module build failed: SyntaxError: "options" is read-only
13:22:32 
13:22:32   33 | 		};
13:22:32   34 | 		$n4Export('main', main);
13:22:32 > 35 | 		options = function options(items, main) {
13:22:32      | 		          ^
13:22:32   36 | 			const options = [];
13:22:32   37 | 			for(const item of iterable(items)) {
13:22:32   38 | 				if (!!item.dependsOn && item.dependsOn === main.id && item.resource && item.resource.classType === 'OPTION') {
13:22:32 
13:22:32 Error
13:22:32     at transpile (/eu.numberfour.online-presence/node_modules/babel-loader/lib/index.js:64:13)
13:22:32     at /eu.numberfour.online-presence/node_modules/babel-loader/lib/fs-cache.js:118:18
13:22:32     at ReadFileContext.callback (/eu.numberfour.online-presence/node_modules/babel-loader/lib/fs-cache.js:31:21)
13:22:32     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
13:22:32  @ ./src-gen/es/eu.numberfour.online-presence/n4/app/reservation/service/reducer/ChooseAppointmentReducer.js 8:1247-1322
13:22:32  @ ./src-gen/es/eu.numberfour.online-presence/n4/ui/pageComponents/reservation/shared/ManageReservations.js
13:22:32  @ ./src-gen/es/eu.numberfour.online-presence/n4/pages/reservation/manage.js
13:22:32  @ ./pages/reservation/manage.js?entry
13:22:32  @ multi ./pages/reservation/manage.js?entry
```

Full [CI failure log](http://build-master.corp.numberfour.eu:8080/view/CI-n4js/job/CI_OnlinePresence/848/console).

**Comment by mor-n4** [comment]
The error does not occur in the n4jsc tool but later in the build pipeline and is reported by babel. The output code seems to be valid and this seems to be a bug in babel.

See https://github.com/babel/babel/issues/6302.

**Comment by mor-n4** [comment]
Added a warning to hint users towards the issue (as per user request).
