### ISSUE TITLE
Runners and testers are registered twice in the N4JSC.jar

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#301]
For the non-OSGI N4JSC.jar it was required to register runners and testers manually. After switching to OSGI version, double invocation throws exceptions (see below).

Notice that registers for runners and testers are much more restrictive in this behaviour, than file extension registers, that simply accept all values.

Since OSGI/non-OSGI setup for N4JSC.jar has not been finalised yet, make forced registers in N4JSC.jar conditional to the mode in which it is running.

```
21498 ERROR TesterRegistry     - Error while reading extensions for extension point org.eclipse.n4js.tester.testers
java.lang.IllegalArgumentException: cannot register two testers with the same ID: org.eclipse.n4js.tester.nodejs.NODEJS_MANGELHAFT
	at org.eclipse.n4js.tester.extension.TesterRegistry.register(TesterRegistry.java:56)
	at org.eclipse.n4js.tester.extension.TesterRegistry.initialize(TesterRegistry.java:115)
	at org.eclipse.n4js.tester.extension.TesterRegistry.getDescriptors(TesterRegistry.java:65)
	at org.eclipse.n4js.hlc.base.testing.HeadlessTester.checkTester(HeadlessTester.java:131)
	at org.eclipse.n4js.hlc.base.testing.HeadlessTester.runTests(HeadlessTester.java:82)
	at org.eclipse.n4js.hlc.base.N4jscBase.doCompileAndTestAndRun(N4jscBase.java:994)
	at org.eclipse.n4js.hlc.base.N4jscBase.doMain(N4jscBase.java:530)
	at org.eclipse.n4js.hlc.base.N4jscBase.main(N4jscBase.java:339)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.n4js.hlc.ProductLauncher.invoke(ProductLauncher.java:196)
	at org.eclipse.n4js.hlc.ProductLauncher.main(ProductLauncher.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
22482 ERROR RunnerRegistry     - Error while reading extensions for extension point org.eclipse.n4js.runner.runners
java.lang.IllegalArgumentException: cannot register two runners with the same ID: org.eclipse.n4js.runner.nodejs.NODEJS
	at org.eclipse.n4js.runner.extension.RunnerRegistry.register(RunnerRegistry.java:56)
	at org.eclipse.n4js.runner.extension.RunnerRegistry.initialize(RunnerRegistry.java:124)
	at org.eclipse.n4js.runner.extension.RunnerRegistry.getDescriptors(RunnerRegistry.java:74)
	at org.eclipse.n4js.runner.extension.RunnerRegistry.getDescriptor(RunnerRegistry.java:83)
	at org.eclipse.n4js.runner.extension.RunnerRegistry.getRunner(RunnerRegistry.java:93)
	at org.eclipse.n4js.runner.extension.RunnerRegistry.getRunner(RunnerRegistry.java:104)
	at org.eclipse.n4js.runner.RunnerFrontEnd.run(RunnerFrontEnd.java:402)
	at org.eclipse.n4js.tester.nodejs.NodeTester.test(NodeTester.java:71)
	at org.eclipse.n4js.tester.TesterFrontEnd.test(TesterFrontEnd.java:178)
	at org.eclipse.n4js.tester.TesterFrontEnd.test(TesterFrontEnd.java:163)
	at org.eclipse.n4js.hlc.base.testing.HeadlessTester.runTests(HeadlessTester.java:99)
	at org.eclipse.n4js.hlc.base.N4jscBase.doCompileAndTestAndRun(N4jscBase.java:994)
	at org.eclipse.n4js.hlc.base.N4jscBase.doMain(N4jscBase.java:530)
	at org.eclipse.n4js.hlc.base.N4jscBase.main(N4jscBase.java:339)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.n4js.hlc.ProductLauncher.invoke(ProductLauncher.java:196)
	at org.eclipse.n4js.hlc.ProductLauncher.main(ProductLauncher.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
```

**Comment by yoosiba** [comment]
fixed in https://github.com/eclipse/n4js/commit/6ae3e46376e960d9e6de6239bfcb13b3d453cf23
