### ISSUE TITLE
Fix failing smoke tests due to flowgraph optimization

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#312]
```
java.lang.AssertionError: java.util.NoSuchElementException
 at org.eclipse.n4js.ExceptionAwareDiagnosticConverter.handleExceptions(ExceptionAwareDiagnosticConverter.java:49)
 at org.eclipse.n4js.ExceptionAwareDiagnosticConverter.convertValidatorDiagnostic(ExceptionAwareDiagnosticConverter.java:38)
 at org.eclipse.xtext.validation.ResourceValidatorImpl.issueFromEValidatorDiagnostic(ResourceValidatorImpl.java:180)
 at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:149)
 at org.eclipse.n4js.validation.N4JSResourceValidator.validate(N4JSResourceValidator.java:97)
 at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
 at org.eclipse.n4js.validation.N4JSResourceValidator.validate(N4JSResourceValidator.java:77)
 at org.eclipse.n4js.analysis.ExceptionAnalyser.getScriptErrors(ExceptionAnalyser.java:77)
 at org.eclipse.n4js.analysis.PositiveAnalyser.analyse(PositiveAnalyser.java:57)
 at org.eclipse.n4js.smoke.tests.Generated1SmokeTest$DefaultSmokeTester.doProcessFile(Generated1SmokeTest.java:47)
 at org.eclipse.n4js.smoke.tests.UniqueScenarioProcessor.processFile(UniqueScenarioProcessor.java:50)
 at org.eclipse.xtext.testing.smoketest.DeltaScenarioProcessor$Adapter.processFile(DeltaScenarioProcessor.java:52)
 at org.eclipse.xtext.testing.smoketest.DeltaScenarioProcessor.processFile(DeltaScenarioProcessor.java:33)
 at org.eclipse.xtext.testing.smoketest.Scenario$1.processInput(Scenario.java:40)
 at org.eclipse.xtext.testing.smoketest.Scenario.processInput(Scenario.java:155)
 at org.eclipse.xtext.testing.smoketest.internal.ParallelPermutingScenarioRunner.doProcess(ParallelPermutingScenarioRunner.java:42)
 at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner.process(AbstractParallelScenarioRunner.java:168)
 at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner$4.evaluate(AbstractParallelScenarioRunner.java:155)
 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
 at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner.runChild(AbstractParallelScenarioRunner.java:93)
 at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner$2.run(AbstractParallelScenarioRunner.java:121)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException
 at java.util.HashMap$HashIterator.nextNode(HashMap.java:1439)
 at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
 at org.eclipse.n4js.flowgraphs.factories.ControlFlowGraphFactory.removeNode(ControlFlowGraphFactory.java:156)
 at org.eclipse.n4js.flowgraphs.factories.ControlFlowGraphFactory.connectComplexNodes(ControlFlowGraphFactory.java:114)
 at org.eclipse.n4js.flowgraphs.factories.ControlFlowGraphFactory.build(ControlFlowGraphFactory.java:59)
 at org.eclipse.n4js.flowgraphs.N4JSFlowAnalyzer.createGraphs(N4JSFlowAnalyzer.java:68)
 at org.eclipse.n4js.validation.validators.N4JSFunctionValidator.checkFlowGraphs(N4JSFunctionValidator.java:143)
 at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:118)
 at org.eclipse.n4js.validation.N4JSValidator$1.invoke(N4JSValidator.java:100)
 at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:312)
 at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)
 at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151)
 at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)
 at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)
 at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
 at org.eclipse.xtext.validation.CancelableDiagnostician.validate(CancelableDiagnostician.java:39)
 at org.eclipse.n4js.utils.validation.PrePostDiagnostician.validate(PrePostDiagnostician.java:56)
 at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:120)
 at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:146)
 ... 22 more
]>
Stacktrace

org.junit.ComparisonFailure: expected:<[@@DoNotCompile
import A from "p/A"
@Force
i]> but was:<[java.lang.AssertionError: java.util.NoSuchElementException
	at org.eclipse.n4js.ExceptionAwareDiagnosticConverter.handleExceptions(ExceptionAwareDiagnosticConverter.java:49)
	at org.eclipse.n4js.ExceptionAwareDiagnosticConverter.convertValidatorDiagnostic(ExceptionAwareDiagnosticConverter.java:38)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.issueFromEValidatorDiagnostic(ResourceValidatorImpl.java:180)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:149)
	at org.eclipse.n4js.validation.N4JSResourceValidator.validate(N4JSResourceValidator.java:97)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at org.eclipse.n4js.validation.N4JSResourceValidator.validate(N4JSResourceValidator.java:77)
	at org.eclipse.n4js.analysis.ExceptionAnalyser.getScriptErrors(ExceptionAnalyser.java:77)
	at org.eclipse.n4js.analysis.PositiveAnalyser.analyse(PositiveAnalyser.java:57)
	at org.eclipse.n4js.smoke.tests.Generated1SmokeTest$DefaultSmokeTester.doProcessFile(Generated1SmokeTest.java:47)
	at org.eclipse.n4js.smoke.tests.UniqueScenarioProcessor.processFile(UniqueScenarioProcessor.java:50)
	at org.eclipse.xtext.testing.smoketest.DeltaScenarioProcessor$Adapter.processFile(DeltaScenarioProcessor.java:52)
	at org.eclipse.xtext.testing.smoketest.DeltaScenarioProcessor.processFile(DeltaScenarioProcessor.java:33)
	at org.eclipse.xtext.testing.smoketest.Scenario$1.processInput(Scenario.java:40)
	at org.eclipse.xtext.testing.smoketest.Scenario.processInput(Scenario.java:155)
	at org.eclipse.xtext.testing.smoketest.internal.ParallelPermutingScenarioRunner.doProcess(ParallelPermutingScenarioRunner.java:42)
	at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner.process(AbstractParallelScenarioRunner.java:168)
	at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner$4.evaluate(AbstractParallelScenarioRunner.java:155)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner.runChild(AbstractParallelScenarioRunner.java:93)
	at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner$2.run(AbstractParallelScenarioRunner.java:121)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by qtran-n4** [comment]
Fixed
