### ISSUE TITLE
Graceful handling of missing "react" dependency for N4JSX

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#346]
The error case of an `.n4jsx` file located in an N4JS project that does not declare "react" as a project dependency (in the manifest.n4mf) must be handled gracefully.

To reproduce: create a new N4JS project, add a file `R.n4jsx` with the code
```javascript
let elem = <div></div>;
elem;
```
and observe the exceptions thrown. For example:
```
Caused by: java.lang.RuntimeException: Compiler cannot locate JSX backend to use for this resource
	at org.eclipse.n4js.n4jsx.transpiler.utils.JSXBackendHelper.lambda$1(JSXBackendHelper.java:163)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.eclipse.n4js.n4jsx.transpiler.utils.JSXBackendHelper.getAnyBackend(JSXBackendHelper.java:163)
	at org.eclipse.n4js.n4jsx.transpiler.utils.JSXBackendHelper.jsxBackendModuleQualifiedName(JSXBackendHelper.java:148)
	at org.eclipse.n4js.transpiler.es.transform.SanitizeImportsTransformation.patchJSX(SanitizeImportsTransformation.java:120)
	at org.eclipse.n4js.transpiler.es.transform.SanitizeImportsTransformation.transform(SanitizeImportsTransformation.java:88)
	at org.eclipse.n4js.transpiler.AbstractTranspiler.transform(AbstractTranspiler.java:207)
	at org.eclipse.n4js.transpiler.AbstractTranspiler.transpile(AbstractTranspiler.java:147)
	at org.eclipse.n4js.transpiler.es.EcmaScriptTranspiler.transpile(EcmaScriptTranspiler.java:159)
	at org.eclipse.n4js.transpiler.es.EcmaScriptSubGenerator.internalDoGenerate(EcmaScriptSubGenerator.java:151)
	at org.eclipse.n4js.generator.common.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:126)
	... 39 more
```
Also consider other ways of provoking this, e.g. by commenting out the "react" dependency in a manifest, etc.

ACs:
1. make sure all code can cope with this error case (no arbitrary exceptions must be thrown),
2. show an error message at an appropriate location (probably just one per project would be ideal, but maybe one message per `.n4jsx` file would also be ok),
3. ensure that all transitions are properly supported (i.e. all ways of entering and leaving this error case must correctly trigger to the necessary updates in the IDE).

**Comment by yoosiba** [comment]
react is special dependency as it is required for every JSX file. 
Not having that dependency makes every JSX file invalid, since transpiler expects only valid files (i.e. without error markers) this is causing the exception.

1) Adding error marker on the JSX file, would solve this issues. Downside is, every file in the project gets error marker -> large error of markers, that do not help at all.

2) Other approach: do not compile files in the project that has errors in the manifest. That seems reasonable as there is no point of compiling project that is misconfigured. Downside is that files that could be compiled will not be compiled until projects manifest is correct (also manifests of transitive dependencies).
