### ISSUE TITLE
Control flow engine needs to support ExpressionAnnotationList in broken AST

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#378]
Control flow containers are sometimes falsely connected when using an ExpressionAnnotationList which can lead to assertion failures at runtime.

**Comment by yoosiba** [comment]
I've seen this for broken ASTs, e.g.
```javascript
(?:@)
```
this can cause exceptions int CFG, e.g. 
```java
Caused by: java.lang.AssertionError
	at org.eclipse.n4js.flowgraphs.analyses.DeadFlowContext$Backward.setDeadCode(DeadFlowContext.java:128)
	at org.eclipse.n4js.flowgraphs.analyses.DeadFlowContext$Backward.update(DeadFlowContext.java:109)
	at org.eclipse.n4js.flowgraphs.analyses.EdgeGuide.setBranchWalkersReachability(EdgeGuide.java:156)
	at org.eclipse.n4js.flowgraphs.analyses.EdgeGuide.<init>(EdgeGuide.java:68)
	at org.eclipse.n4js.flowgraphs.analyses.EdgeGuide.<init>(EdgeGuide.java:52)
	at org.eclipse.n4js.flowgraphs.analyses.EdgeGuide.getFirstEdgeGuides(EdgeGuide.java:81)
	at org.eclipse.n4js.flowgraphs.analyses.EdgeGuideWorklist.initialize(EdgeGuideWorklist.java:70)
	at org.eclipse.n4js.flowgraphs.analyses.GraphVisitorGuideInternal.walkthrough(GraphVisitorGuideInternal.java:113)
	at org.eclipse.n4js.flowgraphs.analyses.GraphVisitorGuideInternal.walkthrough(GraphVisitorGuideInternal.java:90)
	at org.eclipse.n4js.flowgraphs.analyses.GraphVisitorGuideInternal.walkthroughBackward(GraphVisitorGuideInternal.java:74)
	at org.eclipse.n4js.flowgraphs.analyses.GraphVisitorAnalysis.traverseBackwards(GraphVisitorAnalysis.java:62)
	at org.eclipse.n4js.flowgraphs.analyses.GraphVisitorAnalysis.analyseScript(GraphVisitorAnalysis.java:48)
	at org.eclipse.n4js.flowgraphs.N4JSFlowAnalyzer.accept(N4JSFlowAnalyzer.java:183)
	at org.eclipse.n4js.validation.validators.N4JSFunctionValidator.checkFlowGraphs(N4JSFunctionValidator.java:145)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:118)
	at org.eclipse.n4js.validation.N4JSValidator$1.invoke(N4JSValidator.java:101)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:312)
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)
```
