### ISSUE TITLE
NPE in transpiler when compiling

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#452]
**Stacktrace**

```
Severe error occurred in transpiler=es type=java.lang.NullPointerException.
java.lang.NullPointerException
	at org.eclipse.n4js.transpiler.es.transform.SanitizeImportsTransformation.isUsed(SanitizeImportsTransformation.java:221)
	at org.eclipse.n4js.transpiler.es.transform.SanitizeImportsTransformation.lambda$0(SanitizeImportsTransformation.java:77)
	at org.eclipse.xtext.xbase.lib.internal.BooleanFunctionDelegate.apply(BooleanFunctionDelegate.java:41)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators.addAll(Iterators.java:356)
	at com.google.common.collect.Lists.newArrayList(Lists.java:146)
	at com.google.common.collect.Lists.newArrayList(Lists.java:128)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toList(IterableExtensions.java:573)
	at org.eclipse.n4js.transpiler.es.transform.SanitizeImportsTransformation.assertPostConditions(SanitizeImportsTransformation.java:80)
	at org.eclipse.n4js.transpiler.AbstractTranspiler.transform(AbstractTranspiler.java:213)
	at org.eclipse.n4js.transpiler.AbstractTranspiler.transpile(AbstractTranspiler.java:150)
	at org.eclipse.n4js.transpiler.es.EcmaScriptTranspiler.transpile(EcmaScriptTranspiler.java:159)
	at org.eclipse.n4js.transpiler.es.EcmaScriptSubGenerator.internalDoGenerate(EcmaScriptSubGenerator.java:151)
	at org.eclipse.n4js.generator.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:121)
	at org.eclipse.n4js.generator.N4JSCompositeGenerator.doGenerate(N4JSCompositeGenerator.java:54)
	at org.eclipse.n4js.ui.building.instructions.BuildInstruction.handleChangedContents(BuildInstruction.java:198)
	at org.eclipse.n4js.ui.building.instructions.BuildInstruction.process(BuildInstruction.java:130)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.updateMarkers(N4JSGenerateImmediatelyBuilderState.java:246)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:202)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at org.eclipse.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:77)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by yoosiba** [comment]
check for `null` is easy there, but can you say how to reproduce? We should check why there is null in the intermediate model in the first place (call from `SanitizeImportsTransformation.assertPostConditions()`).

**Comment by mmews-n4** [comment]
both ok for me
