### ISSUE TITLE
NPE during "Mark Occurrences"

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#510]
The following error occurs from time to time during editing when "Mark Occurrences" is enabled. It's annoying since a dialog pops-up.

An internal error occurred during: "Mark Occurrences".

```
java.lang.NullPointerException
	at org.eclipse.n4js.resource.InferredElements$Impl.caseN4MemberDeclaration(InferredElements.java:122)
	at org.eclipse.n4js.resource.InferredElements$Impl.caseN4MemberDeclaration(InferredElements.java:1)
	at org.eclipse.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:1622)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.n4js.resource.InferredElements.collectInferredElements(InferredElements.java:51)
	at org.eclipse.n4js.findReferences.InferredElementsTargetURICollector.doAdd(InferredElementsTargetURICollector.java:65)
	at org.eclipse.xtext.findReferences.TargetURICollector.add(TargetURICollector.java:42)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer.getTargetURIs(DefaultOccurrenceComputer.java:176)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer$1.exec(DefaultOccurrenceComputer.java:127)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer$1.exec(DefaultOccurrenceComputer.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer.createAnnotationMap(DefaultOccurrenceComputer.java:102)
	at org.eclipse.xtext.ui.editor.occurrences.OccurrenceMarker$MarkOccurrenceJob.run(OccurrenceMarker.java:123)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by yoosiba** [comment]
Is it possible to get code example that leads to NPE?
