### ISSUE TITLE
NPE in Mark Occurrences (Xpect related)

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#575]
**Reproduce**
* Open N4JS-IDE, a project, a N4JS file
* enter the snippet below
* enable "Mark Occurrences"
* click on "FIXME"
* see Error-Message-Box in N4JS-IDE and stacktrace in host-Eclipse

```javascript
@@StaticPolyfillAware
export public class B {
    // XPECT FIXME noerrors -->
    public constructor( ) {
    }
}
```

**Stacktrace**

```
!ENTRY org.eclipse.core.jobs 4 2 2018-02-07 17:05:19.560
!MESSAGE An internal error occurred during: "Mark Occurrences".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.n4js.resource.InferredElements$Impl.caseN4MemberDeclaration(InferredElements.java:128)
	at org.eclipse.n4js.resource.InferredElements$Impl.caseN4MemberDeclaration(InferredElements.java:1)
	at org.eclipse.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:1661)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.n4js.resource.InferredElements.collectInferredElements(InferredElements.java:51)
	at org.eclipse.n4js.findReferences.InferredElementsTargetURICollector.doAdd(InferredElementsTargetURICollector.java:65)
	at org.eclipse.xtext.findReferences.TargetURICollector.add(TargetURICollector.java:42)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer.getTargetURIs(DefaultOccurrenceComputer.java:176)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer$1.exec(DefaultOccurrenceComputer.java:127)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer$1.exec(DefaultOccurrenceComputer.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer.createAnnotationMap(DefaultOccurrenceComputer.java:102)
	at org.eclipse.xtext.ui.editor.occurrences.OccurrenceMarker$MarkOccurrenceJob.run(OccurrenceMarker.java:123)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by mmews-n4** [comment]
**another example**

```ts
class A{}
class C {
	public <T> foo(): T {}
}
var c: C;
c.<oo();
```

**stacktrace**
```
!ENTRY org.eclipse.core.jobs 4 2 2018-02-08 11:50:17.924
!MESSAGE An internal error occurred during: "Mark Occurrences".
!STACK 0
org.eclipse.xtext.linking.impl.IllegalNodeException: org.eclipse.n4js.conversion.N4JSValueConverterException: Illegal character in identifier '()' at position 2.
	at org.eclipse.xtext.linking.impl.LinkingHelper.getCrossRefNodeAsString(LinkingHelper.java:72)
	at org.eclipse.n4js.findReferences.ConcreteSyntaxAwareReferenceFinder.toValidInstanceOrNull(ConcreteSyntaxAwareReferenceFinder.java:149)
	at org.eclipse.n4js.findReferences.ConcreteSyntaxAwareReferenceFinder.findLocalReferencesFromElement(ConcreteSyntaxAwareReferenceFinder.java:226)
	at org.eclipse.n4js.findReferences.ConcreteSyntaxAwareReferenceFinder.findLocalReferencesFromElement(ConcreteSyntaxAwareReferenceFinder.java:190)
	at org.eclipse.n4js.findReferences.ConcreteSyntaxAwareReferenceFinder.findLocalReferencesFromElement(ConcreteSyntaxAwareReferenceFinder.java:184)
	at org.eclipse.xtext.findReferences.ReferenceFinder.findReferences(ReferenceFinder.java:139)
	at org.eclipse.n4js.findReferences.ConcreteSyntaxAwareReferenceFinder.findReferences(ConcreteSyntaxAwareReferenceFinder.java:132)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer$1.exec(DefaultOccurrenceComputer.java:139)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer$1.exec(DefaultOccurrenceComputer.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer.createAnnotationMap(DefaultOccurrenceComputer.java:102)
	at org.eclipse.xtext.ui.editor.occurrences.OccurrenceMarker$MarkOccurrenceJob.run(OccurrenceMarker.java:123)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.eclipse.n4js.conversion.N4JSValueConverterException: Illegal character in identifier '()' at position 2.
	at org.eclipse.n4js.conversion.IdentifierValueConverter.convertFromJSIdentifier(IdentifierValueConverter.java:239)
	at org.eclipse.n4js.conversion.IdentifierValueConverter.toValue(IdentifierValueConverter.java:38)
	at org.eclipse.xtext.conversion.impl.AbstractIDValueConverter.toValue(AbstractIDValueConverter.java:35)
	at org.eclipse.xtext.conversion.impl.KeywordAlternativeConverter.toValue(KeywordAlternativeConverter.java:44)
	at org.eclipse.xtext.conversion.impl.KeywordAlternativeConverter.toValue(KeywordAlternativeConverter.java:32)
	at org.eclipse.xtext.conversion.impl.AbstractDeclarativeValueConverterService.toValue(AbstractDeclarativeValueConverterService.java:79)
	at org.eclipse.xtext.linking.impl.LinkingHelper.getCrossRefNodeAsString(LinkingHelper.java:66)
	... 16 more
```

**Comment by mmews-n4** [comment]
both seem to be fixed
