### ISSUE TITLE
Exception thrown when creating project via wizard

### ISSUE THREAD

**Issue by qtran-n4** [eclipse/n4js#67]
To reproduce this bug, do the following steps:

- Start the IDE
- Create a new project via New -> N4JS Project 
- In the console, `java.lang.IllegalArgumentException` is thrown

```
!STACK 0
java.lang.RuntimeException: java.lang.IllegalArgumentException: wrong number of arguments
	at org.eclipse.xtext.service.MethodBasedModule.invokeMethod(MethodBasedModule.java:138)
	at org.eclipse.xtext.service.MethodBasedModule.configure(MethodBasedModule.java:68)
	at org.eclipse.xtext.service.CompoundModule.configure(CompoundModule.java:35)
	at org.eclipse.xtext.service.AbstractGenericModule.configure(AbstractGenericModule.java:33)
	at org.eclipse.xtext.ui.DefaultUiModule.configure(DefaultUiModule.java:134)
	at org.eclipse.n4js.n4jsx.ui.N4JSXUiModule.configure(N4JSXUiModule.java:140)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.spi.Elements.getElements(Elements.java:92)
	at com.google.inject.util.Modules$RealOverriddenModuleBuilder$1.configure(Modules.java:172)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.eclipse.n4js.n4jsx.ui.internal.N4JSXActivator.createInjector(N4JSXActivator.java:74)
	at org.eclipse.n4js.n4jsx.ui.internal.N4JSXActivator.getInjector(N4JSXActivator.java:62)
	at org.eclipse.n4js.n4jsx.ui.N4JSXExecutableExtensionFactory.getInjector(N4JSXExecutableExtensionFactory.java:31)
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:51)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:262)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.initDelegate(RegistryBuilderParticipant.java:182)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.getDelegate(RegistryBuilderParticipant.java:173)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.findJSBuilderParticipant(N4JSGenerateImmediatelyBuilderState.java:257)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:180)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at org.eclipse.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:77)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.xtext.service.MethodBasedModule.invokeMethod(MethodBasedModule.java:136)
	... 44 more
```

**Comment by qtran-n4** [comment]
Set prio to high because creating a new project is done very frequently in the IDE.

**Comment by lbeurerkellner** [comment]
I couldn't reproduce this on the current master. Can you given exact steps to reproduce this?

**Comment by qtran-n4** [comment]
@lbeurerkellner I can't reproduce this bug either. Maybe it happened in the early days when we moved to Eclipse and the system was not stable?
