### ISSUE TITLE
When building n4jsx files, the transpiler throws exceptions in case react is not installed

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#687]
**Reproduce**
* install OPR
* uninstall react using the library manager
* clean/build project "com.enfore.opr.ui.tests"
* see exceptions on console:

```
Severe error occurred in transpiler=es message=cannot locate element factory function of JSX backend for N4JSX resource platform:/resource/com.enfore.opr.ui.tests/test/n4js/tests/n4/ui/input/timeslotselector/TimeSlotSelectorPopOverTest.n4jsx.
java.lang.RuntimeException: cannot locate element factory function of JSX backend for N4JSX resource platform:/resource/com.enfore.opr.ui.tests/test/n4js/tests/n4/ui/input/timeslotselector/TimeSlotSelectorPopOverTest.n4jsx

!ENTRY org.eclipse.n4js.ui 4 0 2018-03-13 11:34:44.956
!MESSAGE Severe error occurred in transpiler=es message=cannot locate element factory function of JSX backend for N4JSX resource platform:/resource/com.enfore.opr.ui.tests/test/n4js/tests/n4/ui/input/timeslotselector/TimeSlotSelectorPopOverTest.n4jsx.
!STACK 0
java.lang.RuntimeException: cannot locate element factory function of JSX backend for N4JSX resource platform:/resource/com.enfore.opr.ui.tests/test/n4js/tests/n4/ui/input/timeslotselector/TimeSlotSelectorPopOverTest.n4jsx
	at org.eclipse.n4js.transpiler.es.transform.JSXTransformation.prepareElementFactoryFunction(JSXTransformation.java:157)
	at org.eclipse.n4js.transpiler.es.transform.JSXTransformation.transform(JSXTransformation.java:123)
	at org.eclipse.n4js.transpiler.AbstractTranspiler.transform(AbstractTranspiler.java:219)
	at org.eclipse.n4js.transpiler.AbstractTranspiler.transpile(AbstractTranspiler.java:153)
	at org.eclipse.n4js.transpiler.es.EcmaScriptTranspiler.transpile(EcmaScriptTranspiler.java:159)
	at org.eclipse.n4js.transpiler.es.EcmaScriptSubGenerator.internalDoGenerate(EcmaScriptSubGenerator.java:153)
	at org.eclipse.n4js.generator.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:123)
	at org.eclipse.n4js.generator.N4JSCompositeGenerator.doGenerate(N4JSCompositeGenerator.java:54)
	at org.eclipse.n4js.ui.building.instructions.BuildInstruction.handleChangedContents(BuildInstruction.java:198)
	at org.eclipse.n4js.ui.building.instructions.BuildInstruction.process(BuildInstruction.java:130)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.updateMarkers(N4JSGenerateImmediatelyBuilderState.java:246)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:202)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at org.eclipse.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:76)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
	at org.eclipse.n4js.transpiler.es.transform.JSXTransformation.prepareElementFactoryFunction(JSXTransformation.java:157)
	at org.eclipse.n4js.transpiler.es.transform.JSXTransformation.transform(JSXTransformation.java:123)
	at org.eclipse.n4js.transpiler.AbstractTranspiler.transform(AbstractTranspiler.java:219)
	at org.eclipse.n4js.transpiler.AbstractTranspiler.transpile(AbstractTranspiler.java:153)
	at org.eclipse.n4js.transpiler.es.EcmaScriptTranspiler.transpile(EcmaScriptTranspiler.java:159)
	at org.eclipse.n4js.transpiler.es.EcmaScriptSubGenerator.internalDoGenerate(EcmaScriptSubGenerator.java:153)
	at org.eclipse.n4js.generator.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:123)
	at org.eclipse.n4js.generator.N4JSCompositeGenerator.doGenerate(N4JSCompositeGenerator.java:54)
	at org.eclipse.n4js.ui.building.instructions.BuildInstruction.handleChangedContents(BuildInstruction.java:198)
	at org.eclipse.n4js.ui.building.instructions.BuildInstruction.process(BuildInstruction.java:130)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.updateMarkers(N4JSGenerateImmediatelyBuilderState.java:246)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:202)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at org.eclipse.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:76)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by mor-n4** [comment]
If a dependency is missing (i.e. react), an error should show up somewhere (manifest, code) and in case of an error the transpiler should not be invoked in the first place.

So the actual problem, here, is that the transpiler is invoked on an erroneous resource.
