### ISSUE TITLE
Mark occurrences causes IDE errors

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#699]
It is unknown, which exact scenarios cause mark occurrences to fail. Below, a stack trace is shown of one such failure. It seems appropriate to add an extensive test suite that triggers mark occurrences on a large code base, e.g. like the smoke test suite or some internal project.

 
stack trace
```
!STACK 0
java.lang.IllegalStateException: cannot link existing TModule to new AST due to hash mismatch: platform:/resource/com.enfore.opr.contract-tests/src/n4js/n4/contract-tests/util/AssertionHelper.n4js
	at org.eclipse.n4js.typesbuilder.N4JSTypesBuilder.relinkTModuleToSource(N4JSTypesBuilder.java:176)
	at org.eclipse.n4js.resource.N4JSDerivedStateComputer.installDerivedState(N4JSDerivedStateComputer.java:57)
	at org.eclipse.n4js.resource.N4JSResource.installDerivedState(N4JSResource.java:849)
	at org.eclipse.n4js.resource.N4JSResource.demandLoadResource(N4JSResource.java:502)
	at org.eclipse.n4js.resource.N4JSResource.access$1(N4JSResource.java:467)
	at org.eclipse.n4js.resource.N4JSResource$ModuleAwareContentsList.resolve(N4JSResource.java:124)
	at org.eclipse.n4js.resource.N4JSResource$ModuleAwareContentsList.resolve(N4JSResource.java:1)
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:348)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObjectForURIFragmentRootSegment(ResourceImpl.java:724)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.getEObjectForURIFragmentRootSegment(DerivedStateAwareResource.java:211)
	at org.eclipse.n4js.resource.N4JSResource.getEObjectForURIFragmentRootSegment(N4JSResource.java:1030)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject(ResourceImpl.java:763)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject(ResourceImpl.java:742)
	at org.eclipse.xtext.resource.XtextResource.access$101(XtextResource.java:63)
	at org.eclipse.xtext.resource.XtextResource$1.getEObject(XtextResource.java:119)
	at org.eclipse.xtext.resource.DefaultFragmentProvider.getEObject(DefaultFragmentProvider.java:28)
	at org.eclipse.xtext.resource.XtextResource.basicGetEObject(XtextResource.java:363)
	at org.eclipse.xtext.resource.XtextResource.getEObject(XtextResource.java:349)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:232)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:120)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.n4js.resource.N4JSResource.doResolveProxy(N4JSResource.java:965)
	at org.eclipse.n4js.utils.emf.ProxyResolvingEObjectImpl.eResolveProxy(ProxyResolvingEObjectImpl.java:32)
	at org.eclipse.n4js.ts.types.impl.TVariableImpl.getAstElement(TVariableImpl.java:307)
	at org.eclipse.n4js.flowgraphs.dataflow.symbols.SymbolOfIdentifierRef.getDeclaration(SymbolOfIdentifierRef.java:45)
	at org.eclipse.n4js.flowgraphs.dataflow.symbols.Symbol.createSymbolKey(Symbol.java:104)
	at org.eclipse.n4js.flowgraphs.dataflow.symbols.Symbol.getSymbolKey(Symbol.java:114)
	at org.eclipse.n4js.flowgraphs.dataflow.symbols.Symbol.hashCode(Symbol.java:130)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.putIfAbsent(HashMap.java:1061)
	at org.eclipse.n4js.flowgraphs.dataflow.symbols.SymbolFactory.create(SymbolFactory.java:126)
	at org.eclipse.n4js.flowgraphs.factories.CFEEffectInfos$InternalEffectInfos.addEffect(CFEEffectInfos.java:199)
	at org.eclipse.n4js.flowgraphs.factories.CFEEffectInfos$InternalEffectInfos.setRead(CFEEffectInfos.java:184)
	at org.eclipse.n4js.flowgraphs.factories.CFEEffectInfos$InternalEffectInfos.caseIdentifierRef(CFEEffectInfos.java:172)
	at org.eclipse.n4js.flowgraphs.factories.CFEEffectInfos$InternalEffectInfos.caseIdentifierRef(CFEEffectInfos.java:1)
	at org.eclipse.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:750)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.n4js.flowgraphs.factories.CFEEffectInfos.set(CFEEffectInfos.java:48)
	at org.eclipse.n4js.flowgraphs.factories.ControlFlowGraphFactory.augmentDataflowInformation(ControlFlowGraphFactory.java:87)
	at org.eclipse.n4js.flowgraphs.analysis.GraphVisitorAnalysis.augmentEffectInformation(GraphVisitorAnalysis.java:116)
	at org.eclipse.n4js.flowgraphs.N4JSFlowAnalyser.augmentEffectInformation(N4JSFlowAnalyser.java:220)
	at org.eclipse.n4js.flowgraphs.N4JSFlowAnalyser.accept(N4JSFlowAnalyser.java:187)
	at org.eclipse.n4js.validation.validators.N4JSFlowgraphValidator.checkFlowGraphs(N4JSFlowgraphValidator.java:102)
	at sun.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:118)
	at org.eclipse.n4js.validation.N4JSValidator$1.invoke(N4JSValidator.java:103)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:312)
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.xtext.validation.CancelableDiagnostician.validate(CancelableDiagnostician.java:39)
	at org.eclipse.n4js.utils.validation.PrePostDiagnostician.validate(PrePostDiagnostician.java:56)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:120)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:146)
	at org.eclipse.n4js.validation.N4JSResourceValidator.validate(N4JSResourceValidator.java:97)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at org.eclipse.n4js.validation.N4JSResourceValidator.validate(N4JSResourceValidator.java:77)
	at org.eclipse.n4js.ui.validation.ManifestAwareResourceValidator.validate(ManifestAwareResourceValidator.java:57)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.addMarkers(DefaultResourceUIValidatorExtension.java:60)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.updateValidationMarkers(DefaultResourceUIValidatorExtension.java:46)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.processDelta(MarkerUpdaterImpl.java:93)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.updateMarkers(MarkerUpdaterImpl.java:63)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.updateMarkers(AbstractBuilderState.java:82)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.updateMarkers(N4JSGenerateImmediatelyBuilderState.java:235)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:202)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at org.eclipse.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:76)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at org.eclipse.n4js.ui.building.N4JSBuildTypeTrackingBuilder.incrementalBuild(N4JSBuildTypeTrackingBuilder.java:53)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.apache.log4j 4 0 2018-03-22 10:59:01.860
!MESSAGE org.eclipse.n4js.resource.N4JSResource  - Error in demandLoadResource for platform:/resource/com.enfore.opr.contract-tests/src/n4js/n4/contract-tests/util/AssertionHelper.n4js

!STACK 0
java.lang.IllegalStateException: cannot link existing TModule to new AST due to hash mismatch: platform:/resource/com.enfore.opr.contract-tests/src/n4js/n4/contract-tests/util/AssertionHelper.n4js
	at org.eclipse.n4js.typesbuilder.N4JSTypesBuilder.relinkTModuleToSource(N4JSTypesBuilder.java:176)
	at org.eclipse.n4js.resource.N4JSDerivedStateComputer.installDerivedState(N4JSDerivedStateComputer.java:57)
	at org.eclipse.n4js.resource.N4JSResource.installDerivedState(N4JSResource.java:849)
	at org.eclipse.n4js.resource.N4JSResource.demandLoadResource(N4JSResource.java:502)
	at org.eclipse.n4js.resource.N4JSResource.access$1(N4JSResource.java:467)
	at org.eclipse.n4js.resource.N4JSResource$ModuleAwareContentsList.resolve(N4JSResource.java:124)
	at org.eclipse.n4js.resource.N4JSResource$ModuleAwareContentsList.resolve(N4JSResource.java:1)
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:348)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObjectForURIFragmentRootSegment(ResourceImpl.java:724)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.getEObjectForURIFragmentRootSegment(DerivedStateAwareResource.java:211)
	at org.eclipse.n4js.resource.N4JSResource.getEObjectForURIFragmentRootSegment(N4JSResource.java:1030)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject(ResourceImpl.java:763)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject(ResourceImpl.java:742)
	at org.eclipse.xtext.resource.XtextResource.access$101(XtextResource.java:63)
	at org.eclipse.xtext.resource.XtextResource$1.getEObject(XtextResource.java:119)
	at org.eclipse.xtext.resource.DefaultFragmentProvider.getEObject(DefaultFragmentProvider.java:28)
	at org.eclipse.xtext.resource.XtextResource.basicGetEObject(XtextResource.java:363)
	at org.eclipse.xtext.resource.XtextResource.getEObject(XtextResource.java:349)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:232)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:120)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.n4js.resource.N4JSResource.doResolveProxy(N4JSResource.java:965)
	at org.eclipse.n4js.utils.emf.ProxyResolvingEObjectImpl.eResolveProxy(ProxyResolvingEObjectImpl.java:32)
	at org.eclipse.n4js.ts.types.impl.TVariableImpl.getAstElement(TVariableImpl.java:307)
	at org.eclipse.n4js.flowgraphs.dataflow.symbols.SymbolOfIdentifierRef.getDeclaration(SymbolOfIdentifierRef.java:45)
	at org.eclipse.n4js.flowgraphs.dataflow.symbols.Symbol.createSymbolKey(Symbol.java:104)
	at org.eclipse.n4js.flowgraphs.dataflow.symbols.Symbol.getSymbolKey(Symbol.java:114)
	at org.eclipse.n4js.flowgraphs.dataflow.symbols.Symbol.hashCode(Symbol.java:130)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.putIfAbsent(HashMap.java:1061)
	at org.eclipse.n4js.flowgraphs.dataflow.symbols.SymbolFactory.create(SymbolFactory.java:126)
	at org.eclipse.n4js.flowgraphs.factories.CFEEffectInfos$InternalEffectInfos.addEffect(CFEEffectInfos.java:199)
	at org.eclipse.n4js.flowgraphs.factories.CFEEffectInfos$InternalEffectInfos.setRead(CFEEffectInfos.java:184)
	at org.eclipse.n4js.flowgraphs.factories.CFEEffectInfos$InternalEffectInfos.caseIdentifierRef(CFEEffectInfos.java:172)
	at org.eclipse.n4js.flowgraphs.factories.CFEEffectInfos$InternalEffectInfos.caseIdentifierRef(CFEEffectInfos.java:1)
	at org.eclipse.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:750)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.n4js.flowgraphs.factories.CFEEffectInfos.set(CFEEffectInfos.java:48)
	at org.eclipse.n4js.flowgraphs.factories.ControlFlowGraphFactory.augmentDataflowInformation(ControlFlowGraphFactory.java:87)
	at org.eclipse.n4js.flowgraphs.analysis.GraphVisitorAnalysis.augmentEffectInformation(GraphVisitorAnalysis.java:116)
	at org.eclipse.n4js.flowgraphs.N4JSFlowAnalyser.augmentEffectInformation(N4JSFlowAnalyser.java:220)
	at org.eclipse.n4js.flowgraphs.N4JSFlowAnalyser.accept(N4JSFlowAnalyser.java:187)
	at org.eclipse.n4js.validation.validators.N4JSFlowgraphValidator.checkFlowGraphs(N4JSFlowgraphValidator.java:102)
	at sun.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:118)
	at org.eclipse.n4js.validation.N4JSValidator$1.invoke(N4JSValidator.java:103)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:312)
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.xtext.validation.CancelableDiagnostician.validate(CancelableDiagnostician.java:39)
	at org.eclipse.n4js.utils.validation.PrePostDiagnostician.validate(PrePostDiagnostician.java:56)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:120)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:146)
	at org.eclipse.n4js.validation.N4JSResourceValidator.validate(N4JSResourceValidator.java:97)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at org.eclipse.n4js.validation.N4JSResourceValidator.validate(N4JSResourceValidator.java:77)
	at org.eclipse.n4js.ui.validation.ManifestAwareResourceValidator.validate(ManifestAwareResourceValidator.java:57)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.addMarkers(DefaultResourceUIValidatorExtension.java:60)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.updateValidationMarkers(DefaultResourceUIValidatorExtension.java:46)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.processDelta(MarkerUpdaterImpl.java:93)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.updateMarkers(MarkerUpdaterImpl.java:63)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.updateMarkers(AbstractBuilderState.java:82)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.updateMarkers(N4JSGenerateImmediatelyBuilderState.java:235)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
	at org.eclipse.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:202)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at org.eclipse.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:76)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at org.eclipse.n4js.ui.building.N4JSBuildTypeTrackingBuilder.incrementalBuild(N4JSBuildTypeTrackingBuilder.java:53)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by aschaefer-n4** [comment]
This issue seems to occur when opening a new file, while the "Mark Occurrences" feature is enabled, followed by double clicking or marking empty spaces. Does not happen every time though.

![image](https://user-images.githubusercontent.com/24318311/39365939-d7ea8182-4a32-11e8-8979-f06b7d0d6d30.png)

**Comment by jpilgrim** [comment]
This bug makes "mark occurrences" almost unusable. I get the message all the time. We really should fix that.
