### ISSUE TITLE
Smoke test Runtime Exception: "Already contains key checkTModuleCreated with child org.eclipse.n4js.smith.TimedDataCollector"

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#755]
This exception appeared when running the smoke tests locally (GeneratedSmokeTestCases3, test_0602 and test_0603). I never saw it on Jenkins.

**stacktrace**
```
java.lang.AssertionError: java.lang.RuntimeException: Already contains key checkTModuleCreated with child org.eclipse.n4js.smith.TimedDataCollector@78ac9fa3
	at org.eclipse.n4js.ExceptionAwareDiagnosticConverter.handleExceptions(ExceptionAwareDiagnosticConverter.java:49)
	at org.eclipse.n4js.ExceptionAwareDiagnosticConverter.convertValidatorDiagnostic(ExceptionAwareDiagnosticConverter.java:38)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.issueFromEValidatorDiagnostic(ResourceValidatorImpl.java:180)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:149)
	at org.eclipse.n4js.validation.N4JSResourceValidator.validate(N4JSResourceValidator.java:97)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at org.eclipse.n4js.validation.N4JSResourceValidator.validate(N4JSResourceValidator.java:77)
	at org.eclipse.n4js.analysis.ExceptionAnalyser.getScriptErrors(ExceptionAnalyser.java:77)
	at org.eclipse.n4js.analysis.PositiveAnalyser.analyse(PositiveAnalyser.java:57)
	at org.eclipse.n4js.smoke.tests.Generated3SmokeTest$DefaultSmokeTester.doProcessFile(Generated3SmokeTest.java:47)
	at org.eclipse.n4js.smoke.tests.UniqueScenarioProcessor.processFile(UniqueScenarioProcessor.java:50)
	at org.eclipse.xtext.testing.smoketest.DeltaScenarioProcessor$Adapter.processFile(DeltaScenarioProcessor.java:52)
	at org.eclipse.xtext.testing.smoketest.DeltaScenarioProcessor.processFile(DeltaScenarioProcessor.java:33)
	at org.eclipse.xtext.testing.smoketest.Scenario$1.processInput(Scenario.java:40)
	at org.eclipse.xtext.testing.smoketest.Scenario.processInput(Scenario.java:155)
	at org.eclipse.xtext.testing.smoketest.internal.ParallelPermutingScenarioRunner.doProcess(ParallelPermutingScenarioRunner.java:42)
	at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner.process(AbstractParallelScenarioRunner.java:168)
	at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner$4.evaluate(AbstractParallelScenarioRunner.java:155)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner.runChild(AbstractParallelScenarioRunner.java:93)
	at org.eclipse.xtext.testing.smoketest.internal.AbstractParallelScenarioRunner$2.run(AbstractParallelScenarioRunner.java:121)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Already contains key checkTModuleCreated with child org.eclipse.n4js.smith.TimedDataCollector@78ac9fa3
	at org.eclipse.n4js.smith.TimedDataCollector.addChild(TimedDataCollector.java:91)
	at org.eclipse.n4js.smith.DataCollectors.get(DataCollectors.java:109)
	at org.eclipse.n4js.smith.DataCollectors.getOrCreateDataCollector(DataCollectors.java:78)
	at org.eclipse.n4js.validation.N4JSValidator$N4JSMethodWrapperCancelable.invoke(N4JSValidator.java:105)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:312)
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.xtext.validation.CancelableDiagnostician.validate(CancelableDiagnostician.java:39)
	at org.eclipse.n4js.utils.validation.PrePostDiagnostician.validate(PrePostDiagnostician.java:56)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:120)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:146)
	... 22 more

```

**Comment by yoosiba** [comment]
When running on Jenkins performance view is not collecting data, so it is not happening there.

I will run smoke tests locally with performance tracking enabled and will try to see what is going on there.
