### ISSUE TITLE
NPE when running code in IDE with runtime code installed from npm

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#968]
Running code in IDE works only with bundled runtime code. Using runtime code in custom version provided by `npm` yields NPE exception (see stacktrace below).

Steps to reproduce

1. use wizard to create `New N4JS Project` with default greeter file
2. in generated greeter file use runtime code explicitly, e.g.  
```typescript
import {join} from "path";
console.log(join);
``` 
3. right click on a greeter file and run it -> should be no errors.
4. modify `package.json` to use runtime code from npm, e.g.: 
```typescript
{
	"name": "test",
	"version": "0.0.1",
	"n4js": {
		"projectType": "library",
		"vendorId": "org.eclipse.n4js",
		"sources": {
			"source": [
				"src"
			]
		},
		"output": "src-gen",
		"requiredRuntimeLibraries": [
			"n4js-runtime-node"
		]
	},
	"dependencies": {
		"n4js-runtime-node": "0.10.0-alpha.7aa7bbc0"
	}
}
```
5. run library manager to setup dependencies
6. right click greeter file to run it -> code is not executed, exception is logged internally

#### stacktrace
```
!ENTRY org.eclipse.ui 4 0 2018-07-10 18:41:35.018
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.google.common.base.Optional.of(Optional.java:85)
	at org.eclipse.n4js.runner.RunnerHelper.getExecModuleAsURI(RunnerHelper.java:252)
	at org.eclipse.n4js.runner.RunnerHelper.lambda$8(RunnerHelper.java:146)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.n4js.runner.RunnerHelper.getExecModuleURI(RunnerHelper.java:155)
	at org.eclipse.n4js.runner.RunnerFrontEnd.getExecModulePathFrom(RunnerFrontEnd.java:386)
	at org.eclipse.n4js.runner.RunnerFrontEnd.configureRuntimeEnvironment(RunnerFrontEnd.java:362)
	at org.eclipse.n4js.runner.RunnerFrontEnd.configureRuntimeEnvironment(RunnerFrontEnd.java:337)
	at org.eclipse.n4js.runner.RunnerFrontEnd.computeDerivedValues(RunnerFrontEnd.java:223)
	at org.eclipse.n4js.runner.RunnerFrontEnd.computeDerivedValues(RunnerFrontEnd.java:213)
	at org.eclipse.n4js.runner.RunnerFrontEnd.createConfiguration(RunnerFrontEnd.java:141)
	at org.eclipse.n4js.runner.RunnerFrontEnd.createConfiguration(RunnerFrontEnd.java:105)
	at org.eclipse.n4js.runner.ui.AbstractRunnerLaunchShortcut.launchFile(AbstractRunnerLaunchShortcut.java:109)
	at org.eclipse.n4js.runner.ui.AbstractRunnerLaunchShortcut.launch(AbstractRunnerLaunchShortcut.java:76)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.launch(LaunchShortcutExtension.java:420)
	at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runInternal(LaunchShortcutAction.java:80)
	at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runWithEvent(LaunchShortcutAction.java:135)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.jface.action.ActionContributionItem.lambda$8(ActionContributionItem.java:1257)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.n4js.product.N4JSApplication.start(N4JSApplication.java:141)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by lbeurerkellner** [comment]
A fix of this was merged in https://github.com/eclipse/n4js/pull/969.

A test for this will be merged in https://github.com/eclipse/n4js/pull/972.
