### ISSUE TITLE
Please decouple "npm" and "node" binary resolution.

### ISSUE THREAD

**Issue by torstenkraemer** [eclipse/n4js#989]
It's just a minor thing, but can lead to some trouble. 
I have a macOS setup (version 10.13.6) and use Hombrew to manage tool installation. 
Node was installed through Homebrew which gives currently those versions for `node` and `npm`:
```$ node --version
v10.6.0
$ npm --version
6.2.0
```

The standard commands on the PATH are symlinks:
```
$ which node; readlink `which node`
/usr/local/bin/node
../Cellar/node/10.6.0/bin/node
$ which npm ; readlink `which npm`
/usr/local/bin/npm
../lib/node_modules/npm/bin/npm-cli.js
```
which end up in completely different folders.

When invoking the headless compiler (n4jscli.jar), it will correctly find and use the `node` command. 
But it deeply resolves the links. So the `node`-path will point to  `/usr/local/Cellar/node/10.6.0/bin/node`

Now when it tries to resolve the `npm` command, it wrongly assumes that is located next to the `node` command and is addressing it as ~`/usr/local/Cellar/node/10.6.0/bin/npm`~ 

The assumption will hold if the system would not resolve symlinks in the first place. 
But with deep link resolution in place it fails to lookup the `npm` command. 

The resulting stack trace is
```
'npm' binary does not exist at /usr/local/Cellar/node/10.6.0/bin/npm. Please check your preferences.
org.eclipse.n4js.hlc.base.ExitCodeException: 'npm' binary does not exist at /usr/local/Cellar/node/10.6.0/bin/npm. Please check your preferences.
	at org.eclipse.n4js.hlc.base.N4jscBase.validateBinaries(N4jscBase.java:606)
	at org.eclipse.n4js.hlc.base.N4jscBase.doMain(N4jscBase.java:499)
	at org.eclipse.n4js.hlc.base.N4jscBase.main(N4jscBase.java:311)
```

HINT: As a work-around I manually linked ```ln -s `which npm` /usr/local/Cellar/node/10.6.0/bin/npm```

**Comment by yoosiba** [comment]
see https://github.com/eclipse/n4js/blob/master/plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/nodejs/NpmBinary.java#L73
